// Paraphrased problem descriptions keyed by leetcode.js `num`. Kept concise
// (2-4 sentences) so the user gets the gist without leaving the page.
// Loaded as a classic script before the inline renderer.

const leetcodeDescriptions = {
  // ── Arrays & Hashing ──
  1: 'Given an integer array <code>nums</code> and an integer <code>target</code>, return the indices of the two numbers that add up to <code>target</code>. Each input has exactly one valid answer, and you may not reuse the same element twice. The two indices may be returned in any order.<br><br><strong>Example:</strong> <code>nums = [2,7,11,15]</code>, <code>target = 9</code> &rarr; <code>[0,1]</code> because <code>nums[0] + nums[1] = 2 + 7 = 9</code>.<br><strong>Constraints:</strong> 2 &le; nums.length &le; 10^4; &minus;10^9 &le; nums[i], target &le; 10^9; exactly one valid answer exists.',
  2: 'Given an array <code>prices</code> where <code>prices[i]</code> is the stock price on day <em>i</em>, find the maximum profit from a single buy/sell transaction: you must buy on one day and sell on a strictly later day. If no profitable transaction is possible, return <code>0</code>.<br><br><strong>Example:</strong> <code>prices = [7,1,5,3,6,4]</code> &rarr; <code>5</code> by buying on day 1 at price <code>1</code> and selling on day 4 at price <code>6</code> (<code>6 &minus; 1 = 5</code>); buying earlier at 7 would never beat this.<br><strong>Constraints:</strong> 1 &le; prices.length &le; 10^5; 0 &le; prices[i] &le; 10^4.',
  3: 'Given an integer array <code>nums</code>, return <code>true</code> if any value appears at least twice in the array, and <code>false</code> if every element is distinct.<br><br><strong>Example:</strong> <code>nums = [1,2,3,1]</code> &rarr; <code>true</code> because the value <code>1</code> appears at indices 0 and 3; by contrast <code>nums = [1,2,3,4]</code> &rarr; <code>false</code>.<br><strong>Constraints:</strong> 1 &le; nums.length &le; 10^5; &minus;10^9 &le; nums[i] &le; 10^9.',
  4: 'Given two strings <code>s</code> and <code>t</code>, return <code>true</code> if <code>t</code> is an anagram of <code>s</code> — that is, it uses exactly the same characters with the same multiplicities, just possibly reordered.<br><br><strong>Example:</strong> <code>s = "anagram"</code>, <code>t = "nagaram"</code> &rarr; <code>true</code>; whereas <code>s = "rat"</code>, <code>t = "car"</code> &rarr; <code>false</code> because the letter counts differ.<br><strong>Constraints:</strong> 1 &le; s.length, t.length &le; 5 &middot; 10^4; lowercase English letters.',
  5: 'Given an array of strings <code>strs</code>, group together all strings that are anagrams of one another (use the same letters with the same counts). Return the answer as a list of lists; both the groups and the strings within them may appear in any order.<br><br><strong>Example:</strong> <code>strs = ["eat","tea","tan","ate","nat","bat"]</code> &rarr; <code>[["eat","tea","ate"],["tan","nat"],["bat"]]</code> because the first three share the sorted key <code>aet</code>, the next two share <code>ant</code>, and <code>bat</code> stands alone.<br><strong>Constraints:</strong> 1 &le; strs.length &le; 10^4; 0 &le; strs[i].length &le; 100; lowercase English letters.',
  6: 'Given an integer array <code>nums</code> and an integer <code>k</code>, return the <code>k</code> most frequently occurring elements. The answer may be returned in any order, and the test cases guarantee it is unique.<br><br><strong>Example:</strong> <code>nums = [1,1,1,2,2,3]</code>, <code>k = 2</code> &rarr; <code>[1,2]</code> because <code>1</code> occurs three times and <code>2</code> twice, the two highest counts, leaving <code>3</code> (one occurrence) out.<br><strong>Constraints:</strong> 1 &le; nums.length &le; 10^5; k is in the range [1, number of distinct elements].',
  7: 'Given an integer array <code>nums</code>, return an array <code>answer</code> where <code>answer[i]</code> is the product of every element of <code>nums</code> except <code>nums[i]</code>. You must solve it without using the division operator and in O(n) time. The trick is to combine a prefix-product pass with a suffix-product pass.<br><br><strong>Example:</strong> <code>nums = [1,2,3,4]</code> &rarr; <code>[24,12,8,6]</code> because, e.g., <code>answer[0] = 2&middot;3&middot;4 = 24</code> and <code>answer[2] = 1&middot;2&middot;4 = 8</code>.<br><strong>Constraints:</strong> 2 &le; n &le; 10^5; every prefix/suffix product fits in a 32-bit int; the answer is guaranteed to fit in a 32-bit int.',
  8: 'Given a partially filled 9&times;9 Sudoku board (empty cells marked <code>\'.\'</code>), decide whether the current configuration is valid. Only the already-filled cells must be checked: no digit may repeat within any single row, any single column, or any of the nine 3&times;3 sub-boxes. The board need not be solvable &mdash; only the existing entries are validated.<br><br><strong>Example:</strong> a board whose first row is <code>[5,3,.,.,7,.,.,.,.]</code> with no conflicting duplicates returns <code>true</code>; placing a second <code>5</code> in that same row, column, or box returns <code>false</code>.<br><strong>Constraints:</strong> board is exactly 9&times;9; each cell is a digit <code>\'1\'</code>&ndash;<code>\'9\'</code> or <code>\'.\'</code>.',
  9: 'Given an unsorted integer array <code>nums</code>, return the length of the longest run of consecutive integers present in the array (values differing by 1, in any order). The catch is the required <code>O(n)</code> time, which rules out simply sorting first.<br><br><strong>Example:</strong> <code>nums = [100,4,200,1,3,2]</code> &rarr; <code>4</code>, since the consecutive run <code>1,2,3,4</code> has length 4.<br><strong>Constraints:</strong> 0 &le; n &le; 10^5; values may be negative and may repeat.',
  10: 'Design a codec that encodes a <code>List&lt;String&gt;</code> into one flat string and decodes that string back into the exact original list. The strings may contain <em>any</em> characters &mdash; including digits, <code>\'#\'</code>, or whatever delimiter you might pick &mdash; so the scheme must be unambiguous regardless of payload.<br><br><strong>Example:</strong> <code>["abc","","de#f"]</code> encodes to <code>3#abc0#5#de#f</code> and decodes back to <code>["abc","","de#f"]</code> exactly.<br><strong>Constraints:</strong> 0 &le; list size &le; 200; each string length 0 &le; len &le; 200; any ASCII characters allowed.',
  11: 'Given an integer array <code>nums</code>, find the contiguous, non-empty subarray with the largest sum and return that sum. The array may contain negative numbers, so the answer is not simply the sum of all positives.<br><br><strong>Example:</strong> <code>nums = [-2,1,-3,4,-1,2,1,-5,4]</code> &rarr; <code>6</code>, from the subarray <code>[4,-1,2,1]</code>.<br><strong>Constraints:</strong> 1 &le; n &le; 10^5; &minus;10^4 &le; nums[i] &le; 10^4.',
  12: 'Given an integer array <code>nums</code>, find the contiguous, non-empty subarray whose elements multiply to the largest product, and return that product. Unlike the max-sum version, negative numbers and zeros make this tricky: a very negative running product can flip to a very large positive one after the next negative element.<br><br><strong>Example:</strong> <code>nums = [2,3,-2,4]</code> &rarr; <code>6</code> from <code>[2,3]</code>; <code>nums = [-2,3,-4]</code> &rarr; <code>24</code> from the whole array.<br><strong>Constraints:</strong> 1 &le; n &le; 2&middot;10^4; the product of any prefix fits in a 32-bit int.',
  13: 'Given an integer array <code>nums</code>, move all <code>0</code>s to the end while preserving the relative order of the non-zero elements. You must modify the array <em>in place</em> without allocating a copy.<br><br><strong>Example:</strong> <code>nums = [0,1,0,3,12]</code> &rarr; <code>[1,3,12,0,0]</code>; the non-zeros keep their original order.<br><strong>Constraints:</strong> 1 &le; n &le; 10^4; &minus;2^31 &le; nums[i] &le; 2^31&minus;1; minimize the number of writes.',
  14: 'Given an array <code>nums</code> with <code>n</code> objects colored red (<code>0</code>), white (<code>1</code>), or blue (<code>2</code>), sort them in place so that all 0s come first, then all 1s, then all 2s. You must do it in a single pass without using a library sort and with constant extra space.<br><br><strong>Example:</strong> <code>nums = [2,0,2,1,1,0]</code> &rarr; <code>[0,0,1,1,2,2]</code>.<br><strong>Constraints:</strong> 1 &le; n &le; 300; each <code>nums[i]</code> is 0, 1, or 2; aim for a one-pass, O(1)-space solution.',
  15: 'Given an unsorted integer array <code>nums</code>, return the smallest positive integer that does <strong>not</strong> appear in the array. The answer is always in the range <code>1</code> to <code>n+1</code> (where <code>n = nums.length</code>), since <em>n</em> values can cover at most the first <em>n</em> positive integers. You must run in O(n) time and use O(1) extra space (beyond the input array).<br><br><strong>Example:</strong> <code>nums = [3,4,-1,1]</code> &rarr; <code>2</code>, because <code>1</code> is present but <code>2</code> is the smallest positive that is missing.<br><strong>Constraints:</strong> 1 &le; n &le; 10^5; values may be negative, zero, or larger than n.',
  16: 'Given an array of intervals where <code>intervals[i] = [start, end]</code>, merge every set of overlapping intervals and return an array of the non-overlapping intervals that cover all the input ranges. Two intervals overlap when one\'s start is &le; the other\'s end (touching endpoints count as overlapping, e.g. <code>[1,4]</code> and <code>[4,5]</code> merge into <code>[1,5]</code>).<br><br><strong>Example:</strong> <code>intervals = [[1,3],[2,6],[8,10],[15,18]]</code> &rarr; <code>[[1,6],[8,10],[15,18]]</code>, because <code>[1,3]</code> and <code>[2,6]</code> overlap.<br><strong>Constraints:</strong> 1 &le; n &le; 10^4; 0 &le; start &le; end &le; 10^4.',
  17: 'Given an <code>m &times; n</code> matrix, return all of its elements in spiral order: start at the top-left, walk clockwise (right across the top, down the right side, left across the bottom, up the left side), then spiral inward one layer at a time until every element is visited.<br><br><strong>Example:</strong> <code>matrix = [[1,2,3],[4,5,6],[7,8,9]]</code> &rarr; <code>[1,2,3,6,9,8,7,4,5]</code>.<br><strong>Constraints:</strong> 1 &le; m, n &le; 10; values fit in an int.',
  18: 'Given an <code>n &times; n</code> 2D matrix representing an image, rotate it 90 degrees <strong>clockwise</strong>, modifying the matrix <strong>in-place</strong> (you may not allocate another 2D matrix for the result).<br><br><strong>Example:</strong> <code>matrix = [[1,2,3],[4,5,6],[7,8,9]]</code> &rarr; <code>[[7,4,1],[8,5,2],[9,6,3]]</code>.<br><strong>Constraints:</strong> n == matrix.length == matrix[i].length; 1 &le; n &le; 20.',
  111: 'Given an array of strings <code>strs</code>, find the longest string that is a prefix of <em>every</em> string in the array. A prefix is a leading run of characters starting at index 0. If the strings share no common leading characters, return the empty string <code>""</code>.<br><br><strong>Example:</strong> <code>strs = ["flower","flow","flight"]</code> &rarr; <code>"fl"</code> because every word starts with <code>fl</code> but the third word breaks at the next character (<code>o</code> vs <code>i</code>).<br><strong>Constraints:</strong> 1 &le; strs.length &le; 200; 0 &le; strs[i].length &le; 200; lowercase English letters only.',
  115: 'Given an integer <code>n</code>, return a list of <code>n</code> strings for the numbers <code>1</code> through <code>n</code>. For each number output <code>"Fizz"</code> if it is divisible by 3, <code>"Buzz"</code> if divisible by 5, <code>"FizzBuzz"</code> if divisible by both, and otherwise the number itself as a string.<br><br><strong>Example:</strong> <code>n = 5</code> &rarr; <code>["1","2","Fizz","4","Buzz"]</code>; here 3 is divisible by 3 and 5 is divisible by 5, while a value like 15 would map to <code>"FizzBuzz"</code>.<br><strong>Constraints:</strong> 1 &le; n &le; 10^4.',

  // ── Two Pointers ──
  19: 'Given a string <code>s</code>, return <code>true</code> if it reads the same forward and backward after converting all letters to lowercase and ignoring every non-alphanumeric character (spaces, punctuation, symbols). An empty string (or one with no alphanumeric characters) counts as a palindrome.<br><br><strong>Example:</strong> <code>s = \\"A man, a plan, a canal: Panama\\"</code> &rarr; <code>true</code>, since the cleaned text <code>amanaplanacanalpanama</code> is a palindrome.<br><strong>Constraints:</strong> 1 &le; s.length &le; 2&times;10^5; s is printable ASCII.',
  20: 'Given a <strong>1-indexed</strong> array <code>numbers</code> sorted in non-decreasing order and a <code>target</code>, find the two numbers that add up to <code>target</code> and return their 1-based indices <code>[index1, index2]</code> with <code>index1 &lt; index2</code>. There is exactly one solution, and you must use only constant extra space.<br><br><strong>Example:</strong> <code>numbers = [2,7,11,15]</code>, <code>target = 9</code> &rarr; <code>[1,2]</code> because <code>numbers[0]+numbers[1]=9</code>.<br><strong>Constraints:</strong> 2 &le; n &le; 3&times;10^4; array is sorted; exactly one valid answer.',
  21: 'Given an integer array <code>nums</code>, return all <strong>unique</strong> triplets <code>[a, b, c]</code> with <code>a + b + c == 0</code>. The triplets in the answer must not be duplicates of one another (order within a triplet and order of triplets does not matter).<br><br><strong>Example:</strong> <code>nums = [-1,0,1,2,-1,-4]</code> &rarr; <code>[[-1,-1,2],[-1,0,1]]</code>.<br><strong>Constraints:</strong> 3 &le; n &le; 3000; -10^5 &le; nums[i] &le; 10^5.',
  22: 'Given an integer array <code>height</code> of length <em>n</em> where each value is the height of a vertical line drawn at that x-coordinate, pick two lines that together with the x-axis form a container. Return the <strong>maximum</strong> amount of water such a container can hold. The water area between lines <code>l</code> and <code>r</code> is <code>(r - l) &times; min(height[l], height[r])</code>.<br><br><strong>Example:</strong> <code>height = [1,8,6,2,5,4,8,3,7]</code> &rarr; <code>49</code> (lines at indices 1 and 8: width 7 &times; min(8,7) = 49).<br><strong>Constraints:</strong> 2 &le; n &le; 10^5; 0 &le; height[i] &le; 10^4.',
  23: 'Given <code>n</code> non-negative integers in <code>height</code> representing an elevation map where each bar has width 1, compute how much rainwater is trapped after it rains. Water collects above a bar up to the lower of the tallest walls to its left and right, so the water level at index <em>i</em> is <code>min(maxLeft, maxRight) - height[i]</code> (clamped at zero).<br><br><strong>Example:</strong> <code>height = [0,1,0,2,1,0,1,3,2,1,2,1]</code> &rarr; <code>6</code>.<br><strong>Constraints:</strong> 1 &le; n &le; 2&times;10^4; 0 &le; height[i] &le; 10^5.',
  24: 'Given a sorted integer array <code>nums</code>, remove the duplicates <strong>in-place</strong> so each distinct value appears only once, keeping the relative order. Return the new length <code>k</code>; the first <code>k</code> elements of <code>nums</code> must hold the unique values (what is left beyond index <code>k</code> does not matter).<br><br><strong>Example:</strong> <code>nums = [0,0,1,1,1,2,2,3,3,4]</code> &rarr; <code>k = 5</code> with <code>nums</code> beginning <code>[0,1,2,3,4,...]</code>.<br><strong>Constraints:</strong> 1 &le; n &le; 3&times;10^4; nums is sorted in non-decreasing order.',

  // ── Sliding Window ──
  25: 'Given a string <code>s</code>, return the length of the longest substring that contains no repeating characters. A substring is a contiguous run of characters.<br><br><strong>Example:</strong> <code>s = "abcabcbb"</code> &rarr; <code>3</code> because the longest such substring is <code>"abc"</code>; <code>s = "bbbbb"</code> &rarr; <code>1</code> (just <code>"b"</code>).<br><strong>Constraints:</strong> 0 &le; n &le; 5·10^4; s consists of letters, digits, symbols and spaces.',
  26: 'Given a string <code>s</code> of uppercase English letters and an integer <code>k</code>, you may replace at most <code>k</code> characters with any uppercase letter. Return the length of the longest substring that can be made to contain a single repeated letter after these replacements.<br><br><strong>Example:</strong> <code>s = "AABABBA"</code>, <code>k = 1</code> &rarr; <code>4</code> because replacing one <code>A</code> in <code>"ABAB"</code>... e.g. <code>"AABA"</code>&rarr;<code>"AAAA"</code> gives a length-4 run.<br><strong>Constraints:</strong> 1 &le; n &le; 10^5; 0 &le; k &le; n; uppercase letters only.',
  27: 'Given two strings <code>s</code> and <code>t</code>, return the shortest substring of <code>s</code> that contains every character of <code>t</code> including duplicates (the required multiplicities). If no such window exists, return the empty string <code>""</code>.<br><br><strong>Example:</strong> <code>s = "ADOBECODEBANC"</code>, <code>t = "ABC"</code> &rarr; <code>"BANC"</code>, the smallest window covering A, B and C.<br><strong>Constraints:</strong> 1 &le; m, n &le; 10^5; the answer is unique if it exists; characters may repeat in t.',
  28: 'Given an array <code>prices</code> where <code>prices[i]</code> is the price of a stock on day <code>i</code>, you may buy and sell as many times as you like but hold at most one share at a time (you must sell before buying again). Return the maximum total profit achievable.<br><br><strong>Example:</strong> <code>prices = [7,1,5,3,6,4]</code> &rarr; <code>7</code>: buy at 1 sell at 5 (+4), buy at 3 sell at 6 (+3).<br><strong>Constraints:</strong> 1 &le; n &le; 3·10^4; 0 &le; prices[i] &le; 10^4.',
  29: 'Given two strings <code>s1</code> and <code>s2</code>, return <code>true</code> if <code>s2</code> contains a substring that is a permutation of <code>s1</code> (any reordering of all of s1\'s characters), and <code>false</code> otherwise.<br><br><strong>Example:</strong> <code>s1 = "ab"</code>, <code>s2 = "eidbaooo"</code> &rarr; <code>true</code> because <code>s2</code> contains <code>"ba"</code>, a permutation of <code>"ab"</code>.<br><strong>Constraints:</strong> 1 &le; |s1|, |s2| &le; 10^4; both strings are lowercase English letters.',
  30: 'Given an integer array <code>nums</code> (values may be negative) and an integer <code>k</code>, return the total number of contiguous subarrays whose elements sum to exactly <code>k</code>.<br><br><strong>Example:</strong> <code>nums = [1,1,1]</code>, <code>k = 2</code> &rarr; <code>2</code>: the subarrays <code>[1,1]</code> at indices (0,1) and (1,2).<br><strong>Constraints:</strong> 1 &le; n &le; 2·10^4; −1000 &le; nums[i] &le; 1000; −10^7 &le; k &le; 10^7.',
  31: 'Given an integer array <code>nums</code> and a window size <code>k</code>, the window slides one position at a time from the left to the right end of the array. Return an array containing the maximum value inside each window position.<br><br><strong>Example:</strong> <code>nums = [1,3,-1,-3,5,3,6,7]</code>, <code>k = 3</code> &rarr; <code>[3,3,5,5,6,7]</code> — the max of each consecutive group of 3.<br><strong>Constraints:</strong> 1 &le; n &le; 10^5; −10^4 &le; nums[i] &le; 10^4; 1 &le; k &le; n.',
  114: 'Given an array of positive integers <code>nums</code> and a positive integer <code>target</code>, return the minimal length of a contiguous subarray whose sum is greater than or equal to <code>target</code>. If no such subarray exists, return <code>0</code>.<br><br><strong>Example:</strong> <code>target = 7</code>, <code>nums = [2,3,1,2,4,3]</code> &rarr; <code>2</code> because the subarray <code>[4,3]</code> sums to 7 and has the shortest length.<br><strong>Constraints:</strong> 1 &le; n &le; 10^5; 1 &le; nums[i] &le; 10^4; 1 &le; target &le; 10^9.',

  // ── Stack ──
  32: 'Given a string <code>s</code> containing only the bracket characters <code>()[]{}</code>, determine whether it is well-formed: every opening bracket must be closed by the same type of bracket, and brackets must close in the correct (last-opened, first-closed) order. Return <code>true</code> if valid, otherwise <code>false</code>.<br><br><strong>Example:</strong> <code>s = "([]{})"</code> &rarr; <code>true</code>; <code>s = "([)]"</code> &rarr; <code>false</code> because the <code>)</code> tries to close a <code>[</code>.<br><strong>Constraints:</strong> 1 &le; s.length &le; 10^4; <code>s</code> consists only of <code>()[]{}</code>.',
  33: 'Design a stack that supports the usual <code>push(val)</code>, <code>pop()</code>, and <code>top()</code> operations, plus a <code>getMin()</code> that returns the smallest element currently in the stack &mdash; every operation must run in O(1) time.<br><br><strong>Example:</strong> after <code>push(-2), push(0), push(-3)</code>, <code>getMin()</code> &rarr; <code>-3</code>; then <code>pop()</code>, <code>top()</code> &rarr; <code>0</code>, and <code>getMin()</code> &rarr; <code>-2</code>.<br><strong>Constraints:</strong> -2^31 &le; val &le; 2^31 - 1; <code>pop</code>, <code>top</code>, <code>getMin</code> are only called on a non-empty stack; up to 3 &middot; 10^4 calls.',
  34: 'You are given an array <code>tokens</code> that represents an arithmetic expression in Reverse Polish (postfix) notation, where operators follow their operands. Valid operators are <code>+</code>, <code>-</code>, <code>*</code>, and <code>/</code>; division truncates toward zero. Evaluate the expression and return the resulting integer.<br><br><strong>Example:</strong> <code>tokens = ["2","1","+","3","*"]</code> &rarr; <code>9</code>, evaluated as <code>((2 + 1) * 3)</code>.<br><strong>Constraints:</strong> 1 &le; tokens.length &le; 10^4; each token is an operator or an integer in <code>[-200, 200]</code>; the expression is always valid.',
  35: 'Given an integer array <code>temperatures</code> where <code>temperatures[i]</code> is the temperature on day <code>i</code>, return an array <code>answer</code> such that <code>answer[i]</code> is the number of days you must wait after day <code>i</code> to get a warmer temperature. If no later day is warmer, set <code>answer[i] = 0</code>.<br><br><strong>Example:</strong> <code>temperatures = [73,74,75,71,69,72,76,73]</code> &rarr; <code>[1,1,4,2,1,1,0,0]</code>.<br><strong>Constraints:</strong> 1 &le; temperatures.length &le; 10^5; 30 &le; temperatures[i] &le; 100.',
  36: 'Given an integer array <code>heights</code> where each <code>heights[i]</code> is the height of a histogram bar of width 1, find the area of the largest rectangle that can be formed within the histogram (the rectangle may span several adjacent bars but is limited by the shortest bar it covers).<br><br><strong>Example:</strong> <code>heights = [2,1,5,6,2,3]</code> &rarr; <code>10</code>, from the bars of height 5 and 6 spanning width 2 (<code>5 &times; 2 = 10</code>).<br><strong>Constraints:</strong> 1 &le; heights.length &le; 10^5; 0 &le; heights[i] &le; 10^4.',
  37: 'Given an encoded string, decode it. The encoding rule is <code>k[encoded_string]</code>, meaning the <code>encoded_string</code> inside the brackets is repeated exactly <em>k</em> times, where <em>k</em> is a positive integer. Plain letters appear as-is, and the encoding can be arbitrarily nested. Return the fully expanded string.<br><br><strong>Example:</strong> <code>s = "3[a2[c]]"</code> &rarr; <code>"accaccacc"</code> (the inner <code>2[c]</code> becomes <code>"cc"</code>, then <code>a + cc</code> is repeated 3 times).<br><strong>Constraints:</strong> 1 &le; s.length &le; 30; <code>s</code> contains lowercase letters, digits, and square brackets; all integers <em>k</em> satisfy 1 &le; k &le; 300; the input is always valid.',

  // ── Binary Search ──
  38: 'Given an array <code>nums</code> sorted in ascending order and a <code>target</code> value, return the index of <code>target</code> within <code>nums</code>, or <code>-1</code> if it is not present. The algorithm must run in O(log n) time.<br><br><strong>Example:</strong> <code>nums = [-1,0,3,5,9,12]</code>, <code>target = 9</code> &rarr; <code>4</code>; with <code>target = 2</code> &rarr; <code>-1</code>.<br><strong>Constraints:</strong> 1 &le; nums.length &le; 10^4; -10^4 &lt; nums[i], target &lt; 10^4; all values are unique and <code>nums</code> is sorted ascending.',
  39: 'An ascending sorted array of distinct integers was rotated at some unknown pivot (so it now reads as two sorted runs). Given the rotated array <code>nums</code> and a <code>target</code>, return the index of <code>target</code>, or <code>-1</code> if it is absent. The algorithm must run in O(log n) time.<br><br><strong>Example:</strong> <code>nums = [4,5,6,7,0,1,2]</code>, <code>target = 0</code> &rarr; <code>4</code>; with <code>target = 3</code> &rarr; <code>-1</code>.<br><strong>Constraints:</strong> 1 &le; nums.length &le; 5000; all values are distinct; <code>nums</code> is a rotation of an ascending array.',
  40: 'An ascending sorted array of distinct integers was rotated an unknown number of times. Given the rotated array <code>nums</code>, return its minimum element in O(log n) time.<br><br><strong>Example:</strong> <code>nums = [4,5,6,7,0,1,2]</code> &rarr; <code>0</code>; <code>nums = [3,4,5,1,2]</code> &rarr; <code>1</code>; a non-rotated <code>nums = [1,2,3]</code> &rarr; <code>1</code>.<br><strong>Constraints:</strong> 1 &le; nums.length &le; 5000; all values are distinct; <code>nums</code> is a rotation of an ascending array.',
  41: 'You manage <code>n</code> versions <code>[1..n]</code> and a bad commit has made every later version bad. Given an API <code>boolean isBadVersion(v)</code>, find the first bad version while minimizing the number of API calls.<br><br><strong>Example:</strong> with <code>n = 5</code> and version 4 being the first bad one, <code>isBadVersion(3) = false</code>, <code>isBadVersion(5) = true</code>, <code>isBadVersion(4) = true</code> &rarr; answer <code>4</code>.<br><strong>Constraints:</strong> 1 &le; bad &le; n &le; 2^31 - 1; once a version is bad, all subsequent versions are bad.',
  42: 'Given two sorted integer arrays <code>nums1</code> and <code>nums2</code> of sizes <code>m</code> and <code>n</code>, return the median of the combined sorted array. The overall algorithm must run in O(log(m + n)) time.<br><br><strong>Example:</strong> <code>nums1 = [1,3]</code>, <code>nums2 = [2]</code> &rarr; <code>2.0</code> (merged <code>[1,2,3]</code>); <code>nums1 = [1,2]</code>, <code>nums2 = [3,4]</code> &rarr; <code>2.5</code> (merged <code>[1,2,3,4]</code>, average of 2 and 3).<br><strong>Constraints:</strong> 0 &le; m, n &le; 1000; 1 &le; m + n; -10^6 &le; nums[i] &le; 10^6; both arrays are sorted ascending.',
  43: 'Implement <code>pow(x, n)</code>, which computes <code>x</code> raised to the integer power <code>n</code> (that is, <code>x^n</code>), for any double <code>x</code> and any 32-bit signed integer <code>n</code> (including negative exponents).<br><br><strong>Example:</strong> <code>x = 2.0</code>, <code>n = 10</code> &rarr; <code>1024.0</code>; <code>x = 2.0</code>, <code>n = -2</code> &rarr; <code>0.25</code> (<code>1 / 2^2</code>).<br><strong>Constraints:</strong> -100.0 &lt; x &lt; 100.0; -2^31 &le; n &le; 2^31 - 1; the result fits in a double.',

  // ── Linked List ──
  44: 'Given the head of a singly linked list, reverse the order of its nodes and return the head of the reversed list. The reversal must rewire the <code>next</code> pointers themselves, not merely the values.<br><br><strong>Example:</strong> <code>head = [1,2,3,4,5]</code> &rarr; <code>[5,4,3,2,1]</code>.<br><strong>Constraints:</strong> 0 &le; n &le; 5000; &minus;5000 &le; Node.val &le; 5000.',
  45: 'Given the heads of two sorted singly linked lists, splice their nodes together into one sorted list and return its head. The merge should reuse the existing nodes rather than allocating new ones, and the result must remain in non-decreasing order.<br><br><strong>Example:</strong> <code>a = [1,2,4]</code>, <code>b = [1,3,4]</code> &rarr; <code>[1,1,2,3,4,4]</code>.<br><strong>Constraints:</strong> 0 &le; len(a), len(b) &le; 50; &minus;100 &le; Node.val &le; 100; both inputs already sorted.',
  46: 'Given the head of a singly linked list, determine whether the list contains a cycle — that is, whether some node\'s <code>next</code> pointer eventually revisits an earlier node so traversal never terminates. Return <code>true</code> if a cycle exists and <code>false</code> otherwise.<br><br><strong>Example:</strong> <code>[3,2,0,-4]</code> with the tail linking back to the node at index 1 &rarr; <code>true</code>.<br><strong>Constraints:</strong> 0 &le; n &le; 10^4; &minus;10^5 &le; Node.val &le; 10^5; aim for O(1) memory.',
  47: 'Given the head of a singly linked list and an integer <code>n</code>, remove the <em>n</em>-th node counting from the end of the list and return the head of the modified list. The challenge is to do it in a single pass without first measuring the list\'s length.<br><br><strong>Example:</strong> <code>head = [1,2,3,4,5]</code>, <code>n = 2</code> &rarr; <code>[1,2,3,5]</code> (the node with value 4 is removed).<br><strong>Constraints:</strong> 1 &le; n &le; len &le; 30; &minus;100 &le; Node.val &le; 100; n is always valid.',
  48: 'Given an array of <code>k</code> linked lists, each already sorted in non-decreasing order, merge all of them into a single sorted linked list and return its head. Some of the input lists may be empty.<br><br><strong>Example:</strong> <code>lists = [[1,4,5],[1,3,4],[2,6]]</code> &rarr; <code>[1,1,2,3,4,4,5,6]</code>.<br><strong>Constraints:</strong> 0 &le; k &le; 10^4; 0 &le; list length; total nodes &le; 10^4; &minus;10^4 &le; Node.val &le; 10^4.',
  49: 'Two non-negative integers are represented by linked lists with one decimal digit per node, stored in <strong>reverse</strong> order (least-significant digit first). Add the two numbers and return the sum as a linked list in the same reverse-order format. Neither input has leading zeros except the number 0 itself.<br><br><strong>Example:</strong> <code>a = [2,4,3]</code> (342), <code>b = [5,6,4]</code> (465) &rarr; <code>[7,0,8]</code> (807).<br><strong>Constraints:</strong> 1 &le; len &le; 100; 0 &le; Node.val &le; 9; no leading zeros.',
  50: 'You are given a linked list where every node has a <code>next</code> pointer and an additional <code>random</code> pointer that may point to any node in the list or to <code>null</code>. Construct and return a <strong>deep copy</strong>: a new set of nodes whose next and random pointers mirror the original structure but reference only the copied nodes, never the originals.<br><br><strong>Example:</strong> a list <code>[[7,null],[13,0],[11,4],[10,2],[1,0]]</code> (each pair is <code>[val, random_index]</code>) &rarr; an identical clone with all pointers pointing into the new nodes.<br><strong>Constraints:</strong> 0 &le; n &le; 1000; &minus;10^4 &le; Node.val &le; 10^4; random is a valid node or null.',
  51: 'Given the head of a singly linked list <code>L0 &rarr; L1 &rarr; &hellip; &rarr; Ln</code>, reorder the nodes <strong>in place</strong> to the interleaved pattern <code>L0 &rarr; Ln &rarr; L1 &rarr; Ln-1 &rarr; L2 &rarr; Ln-2 &rarr; &hellip;</code>. You may only change the node links, not the node values.<br><br><strong>Example:</strong> <code>head = [1,2,3,4,5]</code> &rarr; <code>[1,5,2,4,3]</code>.<br><strong>Constraints:</strong> 1 &le; n &le; 5 &middot; 10^4; 1 &le; Node.val &le; 1000; O(1) extra space.',
  52: 'You are given an integer array <code>nums</code> of length <code>n+1</code> where every value lies in the range <code>[1, n]</code>. By the pigeonhole principle at least one value must repeat; in fact exactly one number is duplicated (possibly more than twice). Return that repeated number without modifying the array and using only constant extra space.<br><br><strong>Example:</strong> <code>nums = [3,1,3,4,2]</code> &rarr; <code>3</code> because <code>3</code> appears at indices 0 and 2.<br><strong>Constraints:</strong> 1 &le; n &le; 10^5; nums.length == n+1; 1 &le; nums[i] &le; n; only one repeated value, read-only array, O(1) space.',
  53: 'Design a data structure for a Least Recently Used (LRU) cache with a fixed positive <code>capacity</code>. <code>get(key)</code> returns the cached value or <code>-1</code> if absent, and counts as a use. <code>put(key, value)</code> inserts or updates the key; if this pushes the size past capacity, the entry that was used least recently is evicted. Both operations must run in average O(1) time.<br><br><strong>Example:</strong> capacity 2; <code>put(1,1)</code>, <code>put(2,2)</code>, <code>get(1)</code>&rarr;<code>1</code>, <code>put(3,3)</code> evicts key 2, then <code>get(2)</code>&rarr;<code>-1</code>.<br><strong>Constraints:</strong> 1 &le; capacity &le; 3000; up to 2&middot;10^5 calls; O(1) per get/put.',
  54: 'Given the <code>head</code> of a singly linked list, sort its nodes into ascending order by value and return the new head. The challenge is to do it in O(n log n) time, which rules out simple insertion sort, while ideally keeping extra space to the recursion stack only.<br><br><strong>Example:</strong> <code>4 &rarr; 2 &rarr; 1 &rarr; 3</code> &rarr; <code>1 &rarr; 2 &rarr; 3 &rarr; 4</code>.<br><strong>Constraints:</strong> 0 &le; n &le; 5&middot;10^4 nodes; -10^5 &le; Node.val &le; 10^5; target O(n log n) time.',

  // ── Trees ──
  55: 'Given the <code>root</code> of a binary tree, invert it so that the result is the mirror image of the original: every node\'s left and right subtrees are swapped, all the way down. Return the root of the inverted tree.<br><br><strong>Example:</strong> <code>[4,2,7,1,3,6,9]</code> &rarr; <code>[4,7,2,9,6,3,1]</code> (each level reflected horizontally).<br><strong>Constraints:</strong> 0 &le; n &le; 100 nodes; -100 &le; Node.val &le; 100.',
  56: 'Given the <code>root</code> of a binary tree, return its maximum depth: the number of nodes along the longest path from the root down to the farthest leaf. An empty tree has depth 0 and a single node has depth 1.<br><br><strong>Example:</strong> <code>[3,9,20,null,null,15,7]</code> &rarr; <code>3</code> (path <code>3 &rarr; 20 &rarr; 15</code>).<br><strong>Constraints:</strong> 0 &le; n &le; 10^4 nodes; -100 &le; Node.val &le; 100.',
  57: 'Given the roots <code>p</code> and <code>q</code> of two binary trees, determine whether they are exactly the same: identical in shape and with equal values at every corresponding position. Return <code>true</code> only if both the structure and all node values match.<br><br><strong>Example:</strong> <code>p = [1,2,3]</code>, <code>q = [1,2,3]</code> &rarr; <code>true</code>; <code>p = [1,2]</code>, <code>q = [1,null,2]</code> &rarr; <code>false</code> (the 2 sits on different sides).<br><strong>Constraints:</strong> 0 &le; n &le; 100 nodes per tree; -10^4 &le; Node.val &le; 10^4.',
  58: 'Given the roots of two binary trees <code>root</code> and <code>subRoot</code>, return <code>true</code> if there is any node in <code>root</code> whose subtree is structurally identical to <code>subRoot</code> with the same values. A tree is always considered a subtree of itself.<br><br><strong>Example:</strong> <code>root = [3,4,5,1,2]</code>, <code>subRoot = [4,1,2]</code> &rarr; <code>true</code> (the node 4 and its children match).<br><strong>Constraints:</strong> 1 &le; root nodes &le; 2000; 1 &le; subRoot nodes &le; 1000; -10^4 &le; Node.val &le; 10^4.',
  59: 'Given the <code>root</code> of a binary tree and an integer <code>targetSum</code>, return <code>true</code> if the tree has a root-to-leaf path along which the node values add up to exactly <code>targetSum</code>. A leaf is a node with no children, and an empty tree has no such path.<br><br><strong>Example:</strong> <code>root = [5,4,8,11,null,13,4,7,2]</code>, <code>targetSum = 22</code> &rarr; <code>true</code> via <code>5 &rarr; 4 &rarr; 11 &rarr; 2</code>.<br><strong>Constraints:</strong> 0 &le; n &le; 5000 nodes; -1000 &le; Node.val &le; 1000; -10^9 &le; targetSum &le; 10^9.',
  60: 'Given the root of a binary tree, return <code>true</code> if it is <strong>height-balanced</strong>: for every node, the heights of its left and right subtrees differ by at most 1. An empty tree is balanced.<br><br><strong>Example:</strong> <code>root = [3,9,20,null,null,15,7]</code> &rarr; <code>true</code> (root\'s subtrees have heights 1 and 2, differing by 1); <code>root = [1,2,2,3,3,null,null,4,4]</code> &rarr; <code>false</code> (the left subtree is two levels deeper than the right).<br><strong>Constraints:</strong> 0 &le; n &le; 5000; -10^4 &le; node.val &le; 10^4.',
  61: 'Given the root of a binary tree, return <code>true</code> if the tree is a <strong>mirror image of itself</strong> around its center &mdash; that is, the left subtree is the reflection of the right subtree.<br><br><strong>Example:</strong> <code>root = [1,2,2,3,4,4,3]</code> &rarr; <code>true</code> (the tree reads the same reflected left-to-right); <code>root = [1,2,2,null,3,null,3]</code> &rarr; <code>false</code> (the two <code>3</code> nodes sit on the same side, breaking symmetry).<br><strong>Constraints:</strong> 1 &le; n &le; 1000; -100 &le; node.val &le; 100.',
  62: 'Given the root of a binary tree, return its <strong>level-order traversal</strong>: a list of levels, top to bottom, where each level is the list of node values read left to right.<br><br><strong>Example:</strong> <code>root = [3,9,20,null,null,15,7]</code> &rarr; <code>[[3],[9,20],[15,7]]</code> &mdash; the root forms level 0, its two children level 1, and their children level 2.<br><strong>Constraints:</strong> 0 &le; n &le; 2000; -1000 &le; node.val &le; 1000.',
  63: 'Imagine standing to the <strong>right</strong> of a binary tree; return the values of the nodes you can see, ordered top to bottom. For each level, that is the rightmost node of that level.<br><br><strong>Example:</strong> <code>root = [1,2,3,null,5,null,4]</code> &rarr; <code>[1,3,4]</code> &mdash; level 0 shows <code>1</code>, level 1\'s rightmost is <code>3</code>, and level 2\'s rightmost is <code>4</code> (node <code>5</code> is hidden behind it).<br><strong>Constraints:</strong> 0 &le; n &le; 100; -100 &le; node.val &le; 100.',
  64: 'Given the root of a binary tree, return <code>true</code> if it is a valid <strong>binary search tree</strong>: every node in a node\'s left subtree is <em>strictly</em> less than it, and every node in its right subtree is <em>strictly</em> greater. The rule applies to whole subtrees, not just direct children.<br><br><strong>Example:</strong> <code>root = [5,1,4,null,null,3,6]</code> &rarr; <code>false</code> because <code>3</code> sits in <code>5</code>\'s right subtree yet is less than <code>5</code>; <code>root = [2,1,3]</code> &rarr; <code>true</code>.<br><strong>Constraints:</strong> 1 &le; n &le; 10^4; -2^31 &le; node.val &le; 2^31 - 1.',
  65: 'Given the root of a binary search tree and an integer <code>k</code>, return the <strong>k-th smallest</strong> value among all nodes (1-indexed).<br><br><strong>Example:</strong> <code>root = [3,1,4,null,2]</code>, <code>k = 1</code> &rarr; <code>1</code>; with <code>k = 3</code> &rarr; <code>3</code>. Sorting the values gives <code>[1,2,3,4]</code>, and the k-th entry is the answer.<br><strong>Constraints:</strong> 1 &le; k &le; n &le; 10^4; 0 &le; node.val &le; 10^4.',
  66: 'Given a binary search tree and two of its nodes <code>p</code> and <code>q</code>, return their <strong>lowest common ancestor</strong> &mdash; the deepest node that has both <code>p</code> and <code>q</code> as descendants (a node may be a descendant of itself).<br><br><strong>Example:</strong> <code>root = [6,2,8,0,4,7,9]</code>, <code>p = 2</code>, <code>q = 8</code> &rarr; <code>6</code>, since 2 and 8 lie in different subtrees of 6; with <code>p = 2</code>, <code>q = 4</code> &rarr; <code>2</code> (an ancestor of itself).<br><strong>Constraints:</strong> 2 &le; n &le; 10^5; all node values are unique; <code>p</code> and <code>q</code> exist in the tree.',
  67: 'Given two integer arrays, <code>preorder</code> and <code>inorder</code>, representing the preorder and inorder traversals of the same binary tree with <em>distinct</em> values, reconstruct the tree and return its root.<br><br><strong>Example:</strong> <code>preorder = [3,9,20,15,7]</code>, <code>inorder = [9,3,15,20,7]</code> &rarr; the tree <code>[3,9,20,null,null,15,7]</code>: <code>3</code> is the root (first in preorder), and in inorder everything left of <code>3</code> (<code>9</code>) forms its left subtree, everything right its right subtree.<br><strong>Constraints:</strong> 1 &le; n &le; 3000; values are unique; the two arrays are consistent traversals of one tree.',
  68: 'Given the <code>root</code> of a binary tree, return the maximum sum of any non-empty path. A path is a sequence of nodes where each adjacent pair is joined by an edge, each node appears at most once, and the path need <em>not</em> pass through the root. Because node values may be negative, the best path can be a single node or bend (turn) at some pivot node.<br><br><strong>Example:</strong> tree <code>[-10,9,20,null,null,15,7]</code> &rarr; <code>42</code>, the path <code>15 &rarr; 20 &rarr; 7</code>.<br><strong>Constraints:</strong> 1 &le; n &le; 3&middot;10^4; &minus;1000 &le; <code>Node.val</code> &le; 1000.',
  69: 'Design an algorithm to <strong>serialize</strong> a binary tree into a single string and <strong>deserialize</strong> that string back into the identical tree. There is no restriction on the encoding format as long as the round-trip reproduces the original structure and values, including the exact placement of null children.<br><br><strong>Example:</strong> tree <code>[1,2,3,null,null,4,5]</code> serializes to <code>"1,2,#,#,3,4,#,#,5,#,#,"</code> and deserializes back to the same tree.<br><strong>Constraints:</strong> 0 &le; n &le; 10^4; &minus;1000 &le; <code>Node.val</code> &le; 1000.',
  70: 'Given the <code>root</code> of a binary tree and two distinct nodes <code>p</code> and <code>q</code> that are both guaranteed to exist in the tree, return their <strong>lowest common ancestor</strong> (LCA): the deepest node that has both <code>p</code> and <code>q</code> as descendants. A node is allowed to be a descendant of itself, so if <code>p</code> is an ancestor of <code>q</code> the answer is <code>p</code>. Unlike a BST, there is no ordering to exploit.<br><br><strong>Example:</strong> in <code>[3,5,1,6,2,0,8,null,null,7,4]</code> with <code>p = 5</code>, <code>q = 1</code> &rarr; <code>3</code>.<br><strong>Constraints:</strong> 2 &le; n &le; 10^5; values unique; <code>p</code> &ne; <code>q</code>; both present.',
  71: 'Given the <code>root</code> of a binary tree, return the length of its <strong>diameter</strong>: the number of edges on the longest path between any two nodes. This path may or may not pass through the root, and it does not have to be a root-to-leaf path — it can bend at an internal node, joining the deepest reach of its left subtree with the deepest reach of its right subtree.<br><br><strong>Example:</strong> tree <code>[1,2,3,4,5]</code> &rarr; <code>3</code>, the path <code>4 &rarr; 2 &rarr; 1 &rarr; 3</code> (or <code>5 &rarr; 2 &rarr; 1 &rarr; 3</code>).<br><strong>Constraints:</strong> 1 &le; n &le; 10^4; &minus;100 &le; <code>Node.val</code> &le; 100.',

  // ── Tries ──
  72: 'Implement a <strong>Trie</strong> (prefix tree) supporting three operations: <code>insert(word)</code> adds a word, <code>search(word)</code> returns true only if the exact word was previously inserted, and <code>startsWith(prefix)</code> returns true if any inserted word begins with the given prefix. A Trie stores characters along edges so that words sharing a prefix share a path from the root.<br><br><strong>Example:</strong> after <code>insert("apple")</code>: <code>search("apple")</code> &rarr; <code>true</code>, <code>search("app")</code> &rarr; <code>false</code>, <code>startsWith("app")</code> &rarr; <code>true</code>.<br><strong>Constraints:</strong> 1 &le; word/prefix length &le; 2000; lowercase English letters; up to 3&middot;10^4 calls in total.',
  73: 'Design a <code>WordDictionary</code> data structure with two operations: <code>addWord(word)</code> stores a word, and <code>search(word)</code> returns true if any stored word matches. In a search query the character <code>.</code> is a wildcard that matches <em>any</em> single letter, so a query may match many stored words at once. All other characters must match exactly.<br><br><strong>Example:</strong> after adding <code>"bad"</code>, <code>"dad"</code>, <code>"mad"</code>: <code>search("pad")</code> &rarr; <code>false</code>, <code>search("bad")</code> &rarr; <code>true</code>, <code>search(".ad")</code> &rarr; <code>true</code>, <code>search("b..")</code> &rarr; <code>true</code>.<br><strong>Constraints:</strong> 1 &le; word length &le; 25; lowercase letters for addWord; search words may contain <code>.</code>; up to 10^4 calls.',
  112: 'Given an array of product names <code>products</code> and a <code>searchWord</code>, simulate a search box: after each character the user types, return up to three product names from <code>products</code> that have the typed prefix as a prefix. The three suggestions must be the lexicographically smallest matches. Return a list of these suggestion lists, one per prefix of <code>searchWord</code> (i.e. one for each character typed).<br><br><strong>Example:</strong> <code>products = ["mobile","mouse","moneypot","monitor","mousepad"]</code>, <code>searchWord = "mouse"</code> &rarr; typing <code>"mou"</code> suggests <code>["mouse","mousepad"]</code>, while <code>"m"</code> and <code>"mo"</code> suggest <code>["mobile","moneypot","monitor"]</code>.<br><strong>Constraints:</strong> 1 &le; products.length &le; 1000; 1 &le; searchWord.length &le; 1000; lowercase English letters.',

  // ── Heap / Priority Queue ──
  74: 'Given an integer array <code>nums</code> and an integer <code>k</code>, return the <em>k</em>-th largest element in sorted (descending) order. This is positional rank, <em>not</em> the <em>k</em>-th distinct value, so duplicates count individually.<br><br><strong>Example:</strong> <code>nums = [3,2,1,5,6,4]</code>, <code>k = 2</code> &rarr; <code>5</code> (the sorted order is 6,5,4,3,2,1 and the 2nd is 5).<br><strong>Constraints:</strong> 1 &le; k &le; n &le; 10^5; &minus;10^4 &le; nums[i] &le; 10^4.',
  75: 'Design a data structure that ingests integers from a stream and can report the running median at any time. Support <code>addNum(num)</code> to insert a value and <code>findMedian()</code> to return the median of all values seen so far. The median is the middle element for an odd count, or the average of the two middle elements for an even count.<br><br><strong>Example:</strong> <code>addNum(1)</code>, <code>addNum(2)</code> &rarr; <code>findMedian()</code> = <code>1.5</code>; then <code>addNum(3)</code> &rarr; <code>findMedian()</code> = <code>2.0</code>.<br><strong>Constraints:</strong> &minus;10^5 &le; num &le; 10^5; up to 5&times;10^4 calls.',
  76: 'Given an <code>n&times;n</code> matrix where every row and every column is sorted in ascending order, return the <em>k</em>-th smallest element of the entire matrix in sorted order. Note the kth smallest in sorted order, where duplicate values count separately, not the kth distinct value.<br><br><strong>Example:</strong> <code>matrix = [[1,5,9],[10,11,13],[12,13,15]]</code>, <code>k = 8</code> &rarr; <code>13</code> (sorted: 1,5,9,10,11,12,13,13,15).<br><strong>Constraints:</strong> 1 &le; n &le; 300; 1 &le; k &le; n^2; rows and columns each sorted ascending.',
  77: 'Given a string <code>s</code>, rearrange its characters so that no two adjacent characters are the same. Return any one valid arrangement, or the empty string <code>""</code> if no such arrangement exists (which happens when some character\'s count exceeds <code>(n+1)/2</code>).<br><br><strong>Example:</strong> <code>s = "aab"</code> &rarr; <code>"aba"</code>; <code>s = "aaab"</code> &rarr; <code>""</code> (three a\'s can\'t be separated).<br><strong>Constraints:</strong> 1 &le; s.length &le; 500; s consists of lowercase English letters only.',

  // ── Backtracking ──
  78: 'Given an integer array <code>nums</code> of unique elements, return all possible subsets (the power set). The solution set must not contain duplicate subsets, and the empty subset is included. The subsets and their internal order may be returned in any order.<br><br><strong>Example:</strong> <code>nums = [1,2,3]</code> &rarr; <code>[[],[1],[2],[3],[1,2],[1,3],[2,3],[1,2,3]]</code> (8 = 2^3 subsets).<br><strong>Constraints:</strong> 1 &le; nums.length &le; 10; &minus;10 &le; nums[i] &le; 10; all elements are distinct.',
  79: 'Given an array <code>nums</code> of distinct integers, return all possible permutations (every ordering of all the elements). The answer may be returned in any order, but each permutation must use every element exactly once.<br><br><strong>Example:</strong> <code>nums = [1,2,3]</code> &rarr; <code>[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]</code> (3! = 6 permutations).<br><strong>Constraints:</strong> 1 &le; nums.length &le; 6; &minus;10 &le; nums[i] &le; 10; all integers are distinct.',
  80: 'Given an array <code>candidates</code> of distinct positive integers and a target integer <code>target</code>, return all unique combinations of candidates that sum to <code>target</code>. The same number may be chosen an unlimited number of times, and two combinations are the same if they use the same numbers with the same multiplicities (order ignored).<br><br><strong>Example:</strong> <code>candidates = [2,3,6,7]</code>, <code>target = 7</code> &rarr; <code>[[2,2,3],[7]]</code>.<br><strong>Constraints:</strong> 1 &le; candidates.length &le; 30; 2 &le; candidates[i] &le; 40; 1 &le; target &le; 40; all candidates distinct.',
  81: 'Given a string <code>digits</code> containing digits from <code>2</code>&ndash;<code>9</code>, return all possible letter combinations that the number could spell using the standard telephone keypad mapping (2&rarr;abc, 3&rarr;def, &hellip;, 9&rarr;wxyz). The answer may be returned in any order; an empty input yields an empty list.<br><br><strong>Example:</strong> <code>digits = "23"</code> &rarr; <code>["ad","ae","af","bd","be","bf","cd","ce","cf"]</code>.<br><strong>Constraints:</strong> 0 &le; digits.length &le; 4; each digit is in the range 2&ndash;9.',
  82: 'Given an integer <code>n</code>, generate all combinations of <code>n</code> pairs of well-formed (balanced) parentheses. A string is well-formed when every opening bracket has a matching closing bracket that comes after it and no closing bracket appears without a preceding unmatched opening bracket.<br><br><strong>Example:</strong> <code>n = 3</code> &rarr; <code>["((()))","(()())","(())()","()(())","()()()"]</code> (the 5th Catalan number).<br><strong>Constraints:</strong> 1 &le; n &le; 8.',
  83: 'The n-queens puzzle asks you to place <code>n</code> queens on an <code>n&times;n</code> chessboard so that no two queens attack each other (no two share a row, column, or diagonal). Return all distinct solutions; each is a list of <code>n</code> strings where <code>\'Q\'</code> marks a queen and <code>\'.\'</code> an empty square.<br><br><strong>Example:</strong> <code>n = 4</code> &rarr; <code>2</code> solutions, e.g. <code>[".Q..","...Q","Q...","..Q."]</code>.<br><strong>Constraints:</strong> 1 &le; n &le; 9.',

  // ── Graphs ──
  84: 'Given an <code>m&times;n</code> binary grid where <code>\'1\'</code> marks land and <code>\'0\'</code> marks water, count the number of distinct islands. An island is a maximal group of land cells connected 4-directionally (up/down/left/right); the grid edges count as water.<br><br><strong>Example:</strong> <code>grid = [[1,1,0],[1,0,0],[0,0,1]]</code> &rarr; <code>2</code> &mdash; the connected top-left block is one island and the lone bottom-right cell is another.<br><strong>Constraints:</strong> 1 &le; m, n &le; 300; each cell is <code>\'0\'</code> or <code>\'1\'</code>.',
  85: 'Given a reference to a node in a connected undirected graph, return a deep copy: a new graph with brand-new <code>Node</code> objects whose values and neighbor connections mirror the original exactly. Each node holds an <code>int val</code> and a list of neighbor nodes; the graph may contain cycles.<br><br><strong>Example:</strong> input adjacency <code>[[2,4],[1,3],[2,4],[1,3]]</code> (node i connects to the listed nodes) &rarr; an identical 4-node square graph built from fresh objects.<br><strong>Constraints:</strong> 0 &le; nodes &le; 100; values are unique; no self-loops or repeated edges.',
  86: 'There are <code>numCourses</code> courses labeled <code>0</code>..<code>n-1</code> and a list of prerequisite pairs <code>[a, b]</code> meaning you must take course <code>b</code> before course <code>a</code>. Return <code>true</code> if it is possible to finish every course — equivalently, if the dependency graph has no cycle.<br><br><strong>Example:</strong> <code>n = 2</code>, <code>prereqs = [[1,0]]</code> &rarr; <code>true</code> (take 0 then 1); but <code>[[1,0],[0,1]]</code> &rarr; <code>false</code> (each needs the other).<br><strong>Constraints:</strong> 1 &le; n &le; 2000; 0 &le; pairs &le; 5000; pairs are unique.',
  87: 'Given an <code>m&times;n</code> matrix of cell heights, the Pacific Ocean borders the top and left edges and the Atlantic borders the bottom and right edges. Water flows from a cell to a 4-directional neighbor of equal or lower height. Return every cell from which water can reach <strong>both</strong> oceans.<br><br><strong>Example:</strong> for a 5&times;5 height map, a ridge cell that can drain leftward to the Pacific and rightward to the Atlantic qualifies, e.g. <code>[0,4]</code> and <code>[3,0]</code> among others.<br><strong>Constraints:</strong> 1 &le; m, n &le; 200; 0 &le; height &le; 10^5.',
  88: 'In an <code>m&times;n</code> grid each cell is empty (<code>0</code>), holds a fresh orange (<code>1</code>), or a rotten orange (<code>2</code>). Every minute, any fresh orange that is 4-directionally adjacent to a rotten one also rots. Return the minimum number of minutes until no cell has a fresh orange, or <code>-1</code> if some fresh orange can never rot.<br><br><strong>Example:</strong> <code>[[2,1,1],[1,1,0],[0,1,1]]</code> &rarr; <code>4</code>; but <code>[[2,1,1],[0,1,1],[1,0,1]]</code> &rarr; <code>-1</code> (the bottom-left orange is isolated).<br><strong>Constraints:</strong> 1 &le; m, n &le; 10; cells are 0, 1, or 2.',
  89: 'Given an <code>m&times;n</code> grid of characters and a target <code>word</code>, return <code>true</code> if the word can be spelled out by a path of sequentially adjacent cells. Cells are adjacent horizontally or vertically, and the same cell may not be used twice within one path.<br><br><strong>Example:</strong> <code>board = [[A,B,C,E],[S,F,C,S],[A,D,E,E]]</code>, <code>word = "ABCCED"</code> &rarr; <code>true</code>; <code>word = "ABCB"</code> &rarr; <code>false</code> (would reuse the <code>B</code>).<br><strong>Constraints:</strong> 1 &le; m, n &le; 6; 1 &le; word length &le; 15.',
  90: 'Given an <code>m&times;n</code> grid where <code>-1</code> is a wall, <code>0</code> is a gate, and <code>2147483647</code> (INF) is an empty room, fill each empty room with the distance to its <strong>nearest</strong> gate, measured in 4-directional steps. Rooms that cannot reach any gate keep the value INF. The grid is modified in place.<br><br><strong>Example:</strong> a room two steps from the closest gate (going around a wall) becomes <code>2</code>; a room walled off from every gate stays <code>INF</code>.<br><strong>Constraints:</strong> 1 &le; m, n &le; 250; cells are <code>-1</code>, <code>0</code>, or <code>INF</code>.',
  91: 'Given an <code>m&times;n</code> board of <code>\'X\'</code> and <code>\'O\'</code> cells, capture every region of <code>\'O\'</code>s that is completely surrounded by <code>\'X\'</code>s by flipping those <code>\'O\'</code>s to <code>\'X\'</code>. A region is surrounded only if none of its cells touch the board border; any <code>\'O\'</code> connected (4-directionally) to a border <code>\'O\'</code> survives.<br><br><strong>Example:</strong> in <code>[[X,X,X],[X,O,X],[X,X,X]]</code> the inner <code>O</code> is flipped &rarr; all <code>X</code>; but an <code>O</code> on the edge and its connected group stay <code>O</code>.<br><strong>Constraints:</strong> 1 &le; m, n &le; 200; cells are <code>\'X\'</code> or <code>\'O\'</code>.',

  // ── Advanced Graphs ──
  92: 'You are given a directed weighted graph as a list of edges <code>times[i] = [u, v, w]</code> meaning a signal travels from node <code>u</code> to node <code>v</code> taking <code>w</code> time, the number of nodes <code>n</code> (labelled 1..n), and a source node <code>k</code>. A signal is broadcast from <code>k</code>; return the minimum time for <em>all</em> n nodes to receive it, or <code>-1</code> if some node can never be reached.<br><br><strong>Example:</strong> <code>times = [[2,1,1],[2,3,1],[3,4,1]]</code>, <code>n = 4</code>, <code>k = 2</code> &rarr; <code>2</code> (node 4 is the last to hear it, via 2&rarr;3&rarr;4).<br><strong>Constraints:</strong> 1 &le; k &le; n &le; 100; 1 &le; times.length &le; 6000; 1 &le; w &le; 100.',
  93: 'You are given a list of airline tickets <code>tickets[i] = [from, to]</code>. Reconstruct an itinerary that begins at <code>&quot;JFK&quot;</code> and uses <em>every</em> ticket exactly once. Such an itinerary is guaranteed to exist; if several are possible, return the one whose airport sequence is <strong>lexicographically smallest</strong> when read as a single list.<br><br><strong>Example:</strong> <code>tickets = [[&quot;JFK&quot;,&quot;SFO&quot;],[&quot;JFK&quot;,&quot;ATL&quot;],[&quot;SFO&quot;,&quot;ATL&quot;],[&quot;ATL&quot;,&quot;JFK&quot;],[&quot;ATL&quot;,&quot;SFO&quot;]]</code> &rarr; <code>[&quot;JFK&quot;,&quot;ATL&quot;,&quot;JFK&quot;,&quot;SFO&quot;,&quot;ATL&quot;,&quot;SFO&quot;]</code>.<br><strong>Constraints:</strong> 1 &le; tickets.length &le; 300; all airports are 3 uppercase letters; a valid itinerary exists.',
  94: 'Given two words <code>beginWord</code> and <code>endWord</code> and a dictionary <code>wordList</code>, find the length of the shortest transformation sequence from <code>beginWord</code> to <code>endWord</code>. Each step may change exactly one letter, and every intermediate word (and the end word) must appear in <code>wordList</code>. The length counts the words in the sequence (including both ends). Return <code>0</code> if no such sequence exists.<br><br><strong>Example:</strong> <code>beginWord = &quot;hit&quot;</code>, <code>endWord = &quot;cog&quot;</code>, <code>wordList = [&quot;hot&quot;,&quot;dot&quot;,&quot;dog&quot;,&quot;lot&quot;,&quot;log&quot;,&quot;cog&quot;]</code> &rarr; <code>5</code> (hit &rarr; hot &rarr; dot &rarr; dog &rarr; cog).<br><strong>Constraints:</strong> 1 &le; word length &le; 10; 1 &le; wordList.length &le; 5000; all words are lowercase and equal length.',
  113: 'Given an <code>m &times; n</code> matrix, replace every cell with its <strong>rank</strong>. The rank is a positive integer satisfying three rules: it is as small as possible; if two cells lie in the same row or the same column and hold equal values they must receive the <em>same</em> rank; and if cell A&apos;s value is smaller than cell B&apos;s value and they share a row or column, then rank(A) &lt; rank(B). Return the resulting rank matrix.<br><br><strong>Example:</strong> <code>matrix = [[1,2],[3,4]]</code> &rarr; <code>[[1,2],[2,3]]</code>: the two <code>2</code> and <code>3</code> cells each become one more than the largest rank already fixed in their row/column.<br><strong>Constraints:</strong> 1 &le; m, n &le; 500; −10^9 &le; matrix[i][j] &le; 10^9.',

  // ── DP 1D ──
  95: 'You are climbing a staircase with <code>n</code> steps. Each move you may climb either 1 or 2 steps. Return the number of <strong>distinct</strong> ways you can reach the top.<br><br><strong>Example:</strong> <code>n = 3</code> &rarr; <code>3</code> (1+1+1, 1+2, 2+1).<br><strong>Constraints:</strong> 1 &le; n &le; 45 (the answer fits in a 32-bit int).',
  96: 'Each house on a street holds some amount of money given by <code>nums[i]</code>. You cannot rob two <strong>adjacent</strong> houses (a security system links neighbors). Return the maximum total amount you can rob.<br><br><strong>Example:</strong> <code>nums = [2,7,9,3,1]</code> &rarr; <code>12</code> (rob houses 0, 2, and 4: 2 + 9 + 1).<br><strong>Constraints:</strong> 1 &le; nums.length &le; 100; 0 &le; nums[i] &le; 400.',
  97: 'This is House Robber with the houses arranged in a <strong>circle</strong>: the first and last houses are now adjacent, so they cannot both be robbed. As before you cannot rob two neighboring houses. Given <code>nums[i]</code> for each house, return the maximum amount you can rob.<br><br><strong>Example:</strong> <code>nums = [2,3,2]</code> &rarr; <code>3</code> (you cannot take both house 0 and house 2 since they are adjacent in the circle, so the best is house 1).<br><strong>Constraints:</strong> 1 &le; nums.length &le; 100; 0 &le; nums[i] &le; 1000.',
  98: 'Given an array of coin denominations <code>coins</code> and a target <code>amount</code>, return the <strong>fewest</strong> number of coins needed to total exactly <code>amount</code>. Each denomination may be used an unlimited number of times. If the amount cannot be formed by any combination, return <code>-1</code>.<br><br><strong>Example:</strong> <code>coins = [1,2,5]</code>, <code>amount = 11</code> &rarr; <code>3</code> (5 + 5 + 1).<br><strong>Constraints:</strong> 1 &le; coins.length &le; 12; 1 &le; coins[i] &le; 2^31−1; 0 &le; amount &le; 10^4.',
  99: 'Given an integer array <code>nums</code>, return the length of the longest <strong>strictly increasing</strong> subsequence. A subsequence keeps the original order but may drop elements; it need not be contiguous. Aim for <code>O(n log n)</code>.<br><br><strong>Example:</strong> <code>nums = [10,9,2,5,3,7,101,18]</code> &rarr; <code>4</code> (one such subsequence is <code>[2,3,7,101]</code>).<br><strong>Constraints:</strong> 1 &le; nums.length &le; 2500; −10^4 &le; nums[i] &le; 10^4.',
  100: 'Given a string <code>s</code> and a dictionary of words <code>wordDict</code>, return <code>true</code> if <code>s</code> can be split into a sequence of one or more dictionary words. Words may be reused any number of times, and not every dictionary word has to be used.<br><br><strong>Example:</strong> <code>s = "leetcode"</code>, <code>wordDict = ["leet","code"]</code> &rarr; <code>true</code> because <code>"leet" + "code"</code> covers the whole string.<br><strong>Constraints:</strong> 1 &le; s.length &le; 300; 1 &le; wordDict.length &le; 1000; all dictionary words are distinct.',
  101: 'A message of letters is encoded to digits with the mapping <code>A=1</code>, <code>B=2</code>, &middot;&middot;&middot;, <code>Z=26</code>. Given a non-empty digit string <code>s</code>, return the number of distinct ways to decode it back into letters. A single digit <code>1</code>&ndash;<code>9</code> decodes on its own, and a two-digit chunk <code>10</code>&ndash;<code>26</code> decodes as one letter; a leading <code>0</code> in any chunk is invalid.<br><br><strong>Example:</strong> <code>s = "226"</code> &rarr; <code>3</code> &mdash; it parses as <code>"2 2 6" (BBF)</code>, <code>"22 6" (VF)</code>, or <code>"2 26" (BZ)</code>.<br><strong>Constraints:</strong> 1 &le; s.length &le; 100; <code>s</code> contains only digits.',
  102: 'You are given an integer array <code>nums</code>; you start at index 0 and <code>nums[i]</code> is the maximum length of a single jump forward from position <em>i</em>. Determine whether you can reach the last index.<br><br><strong>Example:</strong> <code>nums = [2,3,1,1,4]</code> &rarr; <code>true</code> (jump 1 step to index 1, then 3 steps to the last index). With <code>nums = [3,2,1,0,4]</code> &rarr; <code>false</code> &mdash; every route stalls at the <code>0</code> at index 3.<br><strong>Constraints:</strong> 1 &le; nums.length &le; 10^4; 0 &le; nums[i] &le; 10^5.',
  103: 'Given an integer array <code>nums</code> where <code>nums[i]</code> is the maximum jump length from position <em>i</em>, and assuming the last index is always reachable, return the <strong>minimum</strong> number of jumps needed to get from index 0 to the last index.<br><br><strong>Example:</strong> <code>nums = [2,3,1,1,4]</code> &rarr; <code>2</code> &mdash; jump from index 0 to index 1 (length 1), then from index 1 to the last index (length 3).<br><strong>Constraints:</strong> 1 &le; nums.length &le; 10^4; 0 &le; nums[i] &le; 1000; a solution is guaranteed to exist.',
  104: 'Given a string <code>s</code>, return the longest contiguous substring of <code>s</code> that reads the same forwards and backwards. If several substrings tie for the longest, any one of them is acceptable.<br><br><strong>Example:</strong> <code>s = "babad"</code> &rarr; <code>"bab"</code> (the substring <code>"aba"</code> is also a valid answer). <code>s = "cbbd"</code> &rarr; <code>"bb"</code>.<br><strong>Constraints:</strong> 1 &le; s.length &le; 1000; <code>s</code> consists of digits and English letters.',

  // ── DP 2D ──
  105: 'A robot sits in the top-left cell of an <code>m &times; n</code> grid and wants to reach the bottom-right cell. It may move only one step <strong>right</strong> or one step <strong>down</strong> at a time. Return how many distinct paths it can take.<br><br><strong>Example:</strong> <code>m = 3</code>, <code>n = 7</code> &rarr; <code>28</code>. For the small grid <code>m = 3</code>, <code>n = 2</code> &rarr; <code>3</code>.<br><strong>Constraints:</strong> 1 &le; m, n &le; 100; the answer is guaranteed to fit in a 32-bit signed integer.',
  106: 'Given two strings <code>text1</code> and <code>text2</code>, return the length of their longest common subsequence. A subsequence keeps the relative order of characters but need not be contiguous, and the answer is the longest sequence common to both strings (0 if none).<br><br><strong>Example:</strong> <code>text1 = "abcde"</code>, <code>text2 = "ace"</code> &rarr; <code>3</code> &mdash; the subsequence <code>"ace"</code> appears in order in both.<br><strong>Constraints:</strong> 1 &le; text1.length, text2.length &le; 1000; both strings consist of lowercase English letters.',
  107: 'Given two strings <code>word1</code> and <code>word2</code>, return the minimum number of single-character operations required to transform <code>word1</code> into <code>word2</code>. The allowed operations are inserting a character, deleting a character, and replacing a character (the Levenshtein distance).<br><br><strong>Example:</strong> <code>word1 = "horse"</code>, <code>word2 = "ros"</code> &rarr; <code>3</code> (<code>horse&rarr;rorse</code> replace, <code>&rarr;rose</code> delete, <code>&rarr;ros</code> delete).<br><strong>Constraints:</strong> 0 &le; word1.length, word2.length &le; 500; both consist of lowercase English letters.',
  108: 'Given an integer array <code>nums</code> of positive integers, return <code>true</code> if the array can be split into two subsets whose element sums are equal.<br><br><strong>Example:</strong> <code>nums = [1,5,11,5]</code> &rarr; <code>true</code> &mdash; it partitions into <code>[1,5,5]</code> and <code>[11]</code>, each summing to 11. <code>nums = [1,2,3,5]</code> &rarr; <code>false</code> (no equal split exists).<br><strong>Constraints:</strong> 1 &le; nums.length &le; 200; 1 &le; nums[i] &le; 100.',
  109: 'Given an <code>m &times; n</code> binary matrix filled with the characters <code>\'0\'</code> and <code>\'1\'</code>, find the largest square whose cells are all <code>\'1\'</code> and return its <strong>area</strong>.<br><br><strong>Example:</strong> for the matrix rows <code>["10100","10111","11111","10010"]</code> &rarr; <code>4</code> &mdash; the biggest all-ones square has side 2, so its area is 4.<br><strong>Constraints:</strong> 1 &le; m, n &le; 300; each cell is <code>\'0\'</code> or <code>\'1\'</code>.',

  // ── Greedy ──
  110: 'There are <code>n</code> gas stations on a circular route; <code>gas[i]</code> is the fuel available at station <em>i</em> and <code>cost[i]</code> is the fuel needed to drive from station <em>i</em> to station <em>i+1</em> (wrapping around). Starting with an empty tank, return the index of the station from which you can complete one full loop, or <code>-1</code> if it is impossible. The answer, when it exists, is unique.<br><br><strong>Example:</strong> <code>gas = [1,2,3,4,5]</code>, <code>cost = [3,4,5,1,2]</code> &rarr; <code>3</code> &mdash; starting at station 3 keeps the tank non-negative the whole way around.<br><strong>Constraints:</strong> n == gas.length == cost.length; 1 &le; n &le; 10^5; 0 &le; gas[i], cost[i] &le; 10^4.',
};
