// MSI Surfaces (M S International, Orange CA) — Software Programmer II/III prep.
// Sources: Glassdoor employer E750335 (4 SWE interview reports, stats public as of
// July 2026; report text is login-gated) and MSI's own job postings #104073
// (Programmer II) and #104110 (Programmer III). The Q&A below is authored prep
// material targeting the stack those postings publish — C#/.NET Core, Angular,
// SQL Server/T-SQL, REST APIs, testing/Git/CI-CD — not transcribed questions.
//
// Answer fields are HTML rendered via innerHTML: use <strong>, <code>, <ul><li>,
// and escape angle brackets inside content as &lt; / &gt;.

const msiProcess = {
  updated: 'July 2026',
  facts: [
    { label: 'Difficulty (Glassdoor)', value: '3.5 / 5' },
    { label: 'Experience positive', value: '75%' },
    { label: 'Typical timeline', value: '~14 days' },
    { label: 'Applied online', value: '75%' },
  ],
  stages: [
    { name: 'HR / recruiter screen', detail: 'Background, motivation, salary expectations. Phone or video, short.' },
    { name: 'Technical interview', detail: 'Reported as basic-to-intermediate questions on .NET Core and SQL; expect the stack below. Sometimes a group panel (38% of reports) with the hiring manager and peers.' },
    { name: 'Written / skills assessment', detail: 'A written objective computer assessment or small project (38% report a skills test; one report describes an Excel-based project). Expect hands-on SQL or code.' },
    { name: 'Final rounds (sometimes)', detail: 'Some candidates report additional in-person rounds up to peer panels and company VPs.' },
  ],
  notes: 'Rated one of the <strong>harder roles MSI hires for</strong> (company average difficulty is 2.6). ' +
    'For the data structures &amp; algorithms side of the skills test, drill the <a href="#leetcode">LeetCode view</a> — ' +
    'both job postings list DS&amp;A knowledge as a requirement. Sources: ' +
    '<a href="https://www.glassdoor.com/Interview/MSI-Software-Engineer-Interview-Questions-EI_IE750335.0,3_KO4,21.htm" target="_blank" rel="noopener">Glassdoor SWE reports</a> (login required for full text), ' +
    '<a href="https://www.msisurfaces.com/careers/jobpost/104073/" target="_blank" rel="noopener">Programmer II posting</a>, ' +
    '<a href="https://www.msisurfaces.com/careers/jobpost/104110/" target="_blank" rel="noopener">Programmer III posting</a>.',
};

const msiSections = [
  {
    id: 'msi-dotnet',
    title: '.NET & C# for Java Developers',
    desc: 'MSI builds in C# / ASP.NET Core. Every question here maps the concept back to the Java equivalent you already know.',
    questions: [
      { d: 'easy',
        q: 'How do the JVM and the .NET CLR compare?',
        a: 'Both are managed runtimes with the same shape: source compiles to an intermediate form (Java bytecode ↔ <strong>CIL</strong>), which a VM (<strong>JVM</strong> ↔ <strong>CLR</strong>) JIT-compiles to native code with garbage collection. Key differences: the CLR has <strong>reified generics</strong> (type info survives at runtime — no erasure), first-class <strong>value types</strong> (<code>struct</code>), and no checked exceptions. Modern .NET (Core / 5+) is cross-platform and open source, like the JVM. If you can explain the JVM, you can explain the CLR — say exactly that in the interview.' },
      { d: 'easy',
        q: 'What are the C# / .NET equivalents of the Java tools you use?',
        a: 'The ecosystem maps almost one-to-one:<ul><li><strong>Spring Boot</strong> ↔ <strong>ASP.NET Core</strong> (web framework + built-in DI + config + hosting)</li><li><strong>Spring DI</strong> (@Component/@Autowired) ↔ <strong>Microsoft.Extensions.DependencyInjection</strong> (registrations in <code>Program.cs</code>)</li><li><strong>JPA/Hibernate</strong> ↔ <strong>Entity Framework Core</strong></li><li><strong>Maven/Gradle</strong> ↔ <strong>NuGet</strong> (packages) + <strong>MSBuild / dotnet CLI</strong> (build)</li><li><strong>JUnit + Mockito</strong> ↔ <strong>xUnit/NUnit + Moq</strong></li><li><strong>Jackson</strong> ↔ <strong>System.Text.Json</strong></li><li><strong>Stream API</strong> ↔ <strong>LINQ</strong></li><li><strong>CompletableFuture</strong> ↔ <strong>Task + async/await</strong></li></ul>' },
      { d: 'easy',
        q: 'What are C# properties, and how do they differ from Java getters and setters?',
        a: 'A property is language-level syntax for a getter/setter pair, used like a field: <code>public string Name { get; set; }</code> replaces a private field plus <code>getName()</code>/<code>setName()</code>. Variants: <code>{ get; }</code> (read-only, set in constructor), <code>{ get; init; }</code> (settable only during object initialization), and expression-bodied getters (<code>public int Area =&gt; W * H;</code>). Java records give you something similar for immutable data; C# also has <code>record</code> types with value equality, like Java records.' },
      { d: 'medium',
        q: 'How does dependency injection work in ASP.NET Core compared to Spring?',
        a: 'Same principle — constructor injection against interfaces — but registration is <strong>explicit</strong> instead of classpath-scanned. In <code>Program.cs</code>: <code>builder.Services.AddScoped&lt;IOrderService, OrderService&gt;();</code> and the framework injects it into any constructor that asks for <code>IOrderService</code>. The three lifetimes map to Spring scopes: <strong>Singleton</strong> (Spring\'s default), <strong>Scoped</strong> (one per HTTP request — like request scope), and <strong>Transient</strong> (new instance every resolve — like prototype). Watch for the classic bug both frameworks share: injecting a scoped dependency into a singleton.' },
      { d: 'medium',
        q: 'How does Entity Framework Core compare to JPA/Hibernate?',
        a: 'EF Core is .NET\'s ORM and the concepts transfer directly: <code>DbContext</code> ↔ <code>EntityManager</code> + persistence context (unit of work with change tracking), <code>DbSet&lt;T&gt;</code> ↔ repository over an entity, and <strong>LINQ queries translate to SQL</strong> the way JPQL/Criteria do. <code>SaveChanges()</code> flushes tracked changes like a JPA flush/commit. Schema evolution uses <strong>EF Migrations</strong> (code-first, generated from model diffs) where a Java shop would use Flyway/Liquibase. One habit difference: EF loads related data via explicit <code>Include()</code> — eager by request — so N+1 problems show up as a missing <code>Include</code>, not a lazy-loading proxy surprise.' },
      { d: 'medium',
        q: 'What is LINQ and what is the difference between IEnumerable and IQueryable?',
        a: 'LINQ is C#\'s integrated query syntax over collections and data sources — the Stream API analog: <code>orders.Where(o =&gt; o.Total &gt; 100).Select(o =&gt; o.Id).ToList()</code>. Like streams, execution is <strong>deferred</strong> until you enumerate (<code>ToList</code>, <code>foreach</code>). The interview-favorite distinction: <code>IEnumerable&lt;T&gt;</code> runs the query <strong>in memory</strong>, while <code>IQueryable&lt;T&gt;</code> builds an expression tree that a provider like EF Core <strong>translates to SQL</strong>. Filtering a <code>DbSet</code> as <code>IQueryable</code> becomes a SQL <code>WHERE</code>; cast it to <code>IEnumerable</code> first and you pull the whole table before filtering client-side.' },
      { d: 'medium',
        q: 'How do async/await and Task compare to Java\'s concurrency model?',
        a: '<code>Task&lt;T&gt;</code> is the analog of <code>CompletableFuture&lt;T&gt;</code>, but the language does the continuation wiring: <code>var user = await http.GetFromJsonAsync&lt;User&gt;(url);</code> reads like blocking code yet frees the thread while waiting — what you\'d write in Java as <code>thenApply</code>/<code>thenCompose</code> chains. ASP.NET Core is async end-to-end, so controller actions returning <code>Task&lt;IActionResult&gt;</code> are the norm, giving the scalability Java now targets with virtual threads. Rules of thumb: async all the way up (don\'t call <code>.Result</code>/<code>.Wait()</code> — deadlock risk), and use <code>CancellationToken</code> for timeouts and aborted requests.' },
      { d: 'medium',
        q: 'How do C# generics differ from Java generics?',
        a: 'C# generics are <strong>reified</strong> — no type erasure. <code>List&lt;int&gt;</code> and <code>List&lt;string&gt;</code> are distinct runtime types, <code>typeof(T)</code> works, and value types aren\'t boxed (no <code>int</code>-vs-<code>Integer</code> split inside collections). Instead of wildcards (<code>? extends T</code>), C# uses declaration-site variance on interfaces: <code>IEnumerable&lt;out T&gt;</code> (covariant, like a producer) and <code>IComparer&lt;in T&gt;</code> (contravariant, like a consumer). Constraints replace bounded types: <code>where T : class, IComparable&lt;T&gt;, new()</code> ≈ <code>&lt;T extends Comparable&lt;T&gt;&gt;</code> plus the ability to require a constructor.' },
      { d: 'hard',
        q: 'Explain class vs struct vs record in C#, and nullable reference types.',
        a: 'Three kinds of type: <strong>class</strong> — reference type on the heap (a Java class); <strong>struct</strong> — a <strong>value type</strong> copied on assignment, no Java equivalent yet (Project Valhalla territory), used for small immutable data like <code>DateTime</code>; <strong>record</strong> — reference type with compiler-generated value equality, <code>ToString</code>, and non-destructive mutation via <code>with</code> — Java records plus <code>withers</code>. Boxing happens when a struct is treated as <code>object</code>, same cost story as Java autoboxing. <strong>Nullable reference types</strong> (on by default in new projects): <code>string</code> is assumed non-null and <code>string?</code> declares nullability, so the compiler flags possible null dereferences — Optional/&#64;Nullable annotations, but enforced by the language.' },
      { d: 'hard',
        q: 'How does .NET garbage collection and resource cleanup compare to the JVM\'s?',
        a: 'Same fundamentals: generational, compacting GC (gen 0/1/2 ↔ young/old), with a <strong>Large Object Heap</strong> for big allocations and Server vs Workstation GC modes (throughput vs latency — think parallel vs G1-style trade-offs). The bigger interview point is <strong>deterministic cleanup</strong>: non-memory resources implement <code>IDisposable</code> and callers wrap them in <code>using var conn = new SqlConnection(...);</code> — exactly try-with-resources/<code>AutoCloseable</code>. Finalizers exist but are discouraged for the same reasons as Java\'s. Mention <code>Span&lt;T&gt;</code>/<code>stackalloc</code> if asked how .NET reduces allocations in hot paths.' },
    ],
  },
  {
    id: 'msi-angular',
    title: 'Angular Basics',
    desc: 'Programmer II asks for Angular 10+, Programmer III for Angular 15+. Enough to build and wire a CRUD front end to a Web API.',
    questions: [
      { d: 'easy',
        q: 'What is Angular and how does an Angular app differ from server-rendered pages?',
        a: 'Angular is a TypeScript framework for <strong>single-page applications</strong>: the browser loads one page, and Angular renders views and handles navigation client-side, calling the server only for JSON data over REST. Compare to Spring MVC + Thymeleaf where every navigation is a full server round-trip returning HTML. An Angular app is built from <strong>components</strong>, uses the CLI (<code>ng new</code>, <code>ng serve</code>, <code>ng build</code>), and talks to a back end like ASP.NET Core purely through HTTP APIs.' },
      { d: 'easy',
        q: 'What is a component in Angular?',
        a: 'The basic UI building block: a TypeScript class with a <code>@Component</code> decorator tying it to an HTML template and styles. <code>@Component({ selector: \'app-order-list\', templateUrl: \'./order-list.component.html\' })</code> — the class holds state and methods, the template binds to them. Components form a tree from the root <code>AppComponent</code> down. Since Angular 15+, <strong>standalone components</strong> (no NgModule required) are the default style — worth mentioning since MSI\'s Programmer III posting asks for 15+.' },
      { d: 'easy',
        q: 'What kinds of data binding does Angular have?',
        a: 'Four, and naming them is a standard screen question:<ul><li><strong>Interpolation</strong> — <code>{{ order.total }}</code> (component → view text)</li><li><strong>Property binding</strong> — <code>[disabled]="isSaving"</code> (component → element property)</li><li><strong>Event binding</strong> — <code>(click)="save()"</code> (view → component)</li><li><strong>Two-way binding</strong> — <code>[(ngModel)]="filter"</code> (both directions, property + event sugar)</li></ul>Structural directives drive the template from state: <code>*ngFor</code> to repeat rows, <code>*ngIf</code> to show/hide (newer versions add <code>@for</code>/<code>@if</code> control-flow syntax).' },
      { d: 'medium',
        q: 'What are Angular services and how does its dependency injection work?',
        a: 'Services hold shared logic and state (API calls, caching) outside components — the analog of Spring <code>@Service</code> beans. Mark the class <code>@Injectable({ providedIn: \'root\' })</code> and it becomes an app-wide singleton, injected via constructor: <code>constructor(private orders: OrderService) {}</code>. Same constructor-injection pattern as Spring and ASP.NET Core, so you can present DI as one concept you apply in all three. Components stay thin (presentation); services own data access — the same layering as controller/service in the back end.' },
      { d: 'medium',
        q: 'What are Observables, and how do they differ from Promises?',
        a: 'Observables (from <strong>RxJS</strong>) are lazy, cancellable streams that can emit many values over time; a Promise eagerly resolves exactly once. Angular\'s <code>HttpClient</code> returns Observables, so a typical call is <code>this.http.get&lt;Order[]&gt;(url).subscribe(data =&gt; this.orders = data)</code> — or better, bind with the <strong>async pipe</strong> (<code>orders$ | async</code>) so Angular subscribes and unsubscribes for you. Know a few operators by name: <code>map</code>, <code>filter</code>, <code>switchMap</code> (e.g. cancel a stale search request when the user types again), <code>debounceTime</code>, <code>catchError</code>. Forgetting to unsubscribe from long-lived subscriptions is the classic memory-leak answer.' },
      { d: 'medium',
        q: 'How does an Angular front end consume an ASP.NET Core Web API?',
        a: 'Provide <code>HttpClient</code>, define a TypeScript interface matching the API\'s JSON shape, and wrap calls in a service: <code>getOrders(): Observable&lt;Order[]&gt; { return this.http.get&lt;Order[]&gt;(\'/api/orders\'); }</code>. Cross-cutting concerns go in <strong>interceptors</strong> — attach the JWT <code>Authorization</code> header, handle 401s centrally (Spring\'s filter/<code>RestTemplate</code> interceptor idea). In dev the Angular CLI runs on its own port, so you either enable <strong>CORS</strong> in ASP.NET Core or use the CLI\'s proxy config; in production the built bundle is often served by the same ASP.NET Core app, no CORS needed.' },
      { d: 'medium',
        q: 'How does routing work in Angular?',
        a: 'The Router maps URL paths to components so the SPA can navigate without reloads: <code>{ path: \'orders/:id\', component: OrderDetailComponent }</code>, rendered into <code>&lt;router-outlet&gt;</code>, linked with <code>routerLink</code>. Read parameters via <code>ActivatedRoute</code>. Two features worth naming: <strong>lazy loading</strong> (<code>loadChildren</code>/<code>loadComponent</code> splits the bundle so feature areas download on first visit) and <strong>guards</strong> (<code>canActivate</code>) for auth-protected routes.' },
      { d: 'medium',
        q: 'How do components communicate with each other?',
        a: 'Parent → child with <code>@Input()</code> properties; child → parent with <code>@Output()</code> + <code>EventEmitter</code>: <code>&lt;app-row [order]="o" (deleted)="onDeleted($event)"&gt;</code>. For unrelated or distant components, share state through a <strong>service</strong> holding an RxJS <code>BehaviorSubject</code> that interested components subscribe to — a lightweight event-bus/state pattern. Full state libraries (NgRx) exist but for a shop MSI\'s size, "shared service with a Subject" is usually the expected answer.' },
      { d: 'easy',
        q: 'Template-driven vs reactive forms — when would you use each?',
        a: '<strong>Template-driven</strong>: logic lives in the template with <code>[(ngModel)]</code> — quick for simple forms. <strong>Reactive</strong>: the form model is built in the component class (<code>FormGroup</code>, <code>FormControl</code>, <code>Validators</code>) — testable, dynamic, and better for anything non-trivial, so it\'s the default choice for enterprise CRUD screens. Both support validation; reactive forms make custom and cross-field validators much cleaner.' },
      { d: 'hard',
        q: 'How does Angular change detection work, and how do you keep it fast?',
        a: 'By default zone.js patches async events (clicks, HTTP, timers) and after each one Angular re-checks component bindings top-down. On large lists that\'s wasteful, so: set <code>changeDetection: ChangeDetectionStrategy.OnPush</code> — the component re-checks only when an <code>@Input</code> reference changes, an event fires in it, or an async pipe emits (this pairs with immutable update patterns); add <code>trackBy</code> to <code>*ngFor</code> so rows aren\'t re-created wholesale. Angular 16+ adds <strong>signals</strong>, fine-grained reactive state that updates only what actually changed — worth naming to show you\'re current with 15+.' },
    ],
  },
  {
    id: 'msi-sql',
    title: 'SQL Server & T-SQL',
    desc: 'The Programmer III posting calls out stored procedures, functions, views, and optimization by name — this is the likeliest skills-test area.',
    questions: [
      { d: 'easy',
        q: 'What is T-SQL, and how does it differ from the standard SQL you know?',
        a: 'T-SQL is SQL Server\'s dialect: standard SQL plus procedural extensions (variables, <code>IF</code>/<code>WHILE</code>, <code>TRY...CATCH</code>, stored procedures). Dialect differences to have ready: <code>TOP n</code> instead of <code>LIMIT</code> (or <code>OFFSET...FETCH</code> for paging), <code>GETDATE()</code>, <code>ISNULL()</code> alongside <code>COALESCE</code>, <code>IDENTITY(1,1)</code> for auto-increment, square-bracket <code>[identifiers]</code>, and string concatenation with <code>+</code>. Management tooling is SSMS; execution plans are first-class there.' },
      { d: 'easy',
        q: 'What is a stored procedure and why would you use one?',
        a: 'A named, precompiled batch of T-SQL stored in the database, invoked with <code>EXEC</code>. Benefits: cached execution plans, one round trip for multi-statement logic, a security boundary (grant EXECUTE without table access — also parameterized, so no SQL injection), and a stable interface over schema details.<div class="ex-label">Example</div><pre><code>CREATE PROCEDURE dbo.GetOrdersByCustomer\n  @CustomerId INT,\n  @Since DATE\nAS\nBEGIN\n  SET NOCOUNT ON;\n  SELECT OrderId, OrderDate, Total\n  FROM dbo.Orders\n  WHERE CustomerId = @CustomerId AND OrderDate &gt;= @Since\n  ORDER BY OrderDate DESC;\nEND</code></pre>' },
      { d: 'easy',
        q: 'What is a view, and when is it useful?',
        a: 'A saved <code>SELECT</code> you query like a table: <code>CREATE VIEW dbo.vActiveOrders AS SELECT ... WHERE Status = \'Active\'</code>. Uses: hide join complexity behind a clean shape, restrict which columns/rows a role can see, and give reporting a stable contract while base tables evolve. A plain view stores no data — it expands into the query at run time. An <strong>indexed (materialized) view</strong> does persist results for expensive aggregations, at the cost of write overhead and schema-binding restrictions.' },
      { d: 'medium',
        q: 'Stored procedure vs user-defined function — what\'s the difference?',
        a: 'Functions return a value and are composable inside queries (<code>SELECT dbo.fn_Tax(Total) FROM Orders</code>, or join a <strong>table-valued function</strong>); they can\'t modify data or manage transactions. Procedures can do side effects, return multiple result sets, and use output parameters — but can\'t sit inside a <code>SELECT</code>. Performance trap worth volunteering: a <strong>scalar</strong> UDF called per-row can execute thousands of times hidden inside a query; inline table-valued functions let the optimizer expand the logic instead.' },
      { d: 'medium',
        q: 'Explain clustered vs nonclustered indexes.',
        a: 'The <strong>clustered index</strong> IS the table — rows are physically ordered by its key, so there\'s exactly one (usually the PK). A <strong>nonclustered index</strong> is a separate B-tree of key → row locator; you can have many. If a query needs columns the index lacks, each hit does a <strong>key lookup</strong> back to the clustered index — fixed by a <strong>covering index</strong>: <code>CREATE INDEX IX_Orders_Customer ON Orders(CustomerId) INCLUDE (OrderDate, Total)</code>. Trade-off to state: every index speeds specific reads but taxes every INSERT/UPDATE/DELETE.' },
      { d: 'medium',
        q: 'A query is slow. Walk through how you\'d diagnose and fix it.',
        a: '<ul><li>Get the <strong>actual execution plan</strong> (SSMS) and <code>SET STATISTICS IO ON</code> — find table scans where you expected seeks, huge logical reads, expensive key lookups.</li><li>Check indexing: missing index on the filter/join columns? Non-covering index causing lookups?</li><li>Check <strong>sargability</strong> — <code>WHERE YEAR(OrderDate) = 2026</code> or a function/implicit conversion on the column kills index use; rewrite as a range: <code>OrderDate &gt;= \'2026-01-01\' AND OrderDate &lt; \'2027-01-01\'</code>.</li><li>Check stale statistics, <code>SELECT *</code> pulling wide rows, and row-by-row logic (cursors/scalar UDFs) that should be set-based.</li><li>Re-measure after each change — one fix at a time.</li></ul>' },
      { d: 'medium',
        q: 'What are window functions? Find each customer\'s most recent order.',
        a: 'Window functions compute over a partition of rows <em>without collapsing them</em> — the classic dedup/top-N-per-group tool and a very common written-test task:<div class="ex-label">Example</div><pre><code>SELECT OrderId, CustomerId, OrderDate, Total\nFROM (\n  SELECT o.*, ROW_NUMBER() OVER (\n    PARTITION BY CustomerId ORDER BY OrderDate DESC) AS rn\n  FROM dbo.Orders o\n) t\nWHERE rn = 1;</code></pre>Know the family: <code>ROW_NUMBER</code> vs <code>RANK</code>/<code>DENSE_RANK</code> (tie handling), <code>LAG</code>/<code>LEAD</code> (compare to previous row), and aggregates with <code>OVER()</code> for running totals.' },
      { d: 'medium',
        q: 'Temp tables vs table variables vs CTEs — when do you reach for each?',
        a: '<strong>CTE</strong> (<code>WITH x AS (...)</code>): readability and recursion; it\'s inlined into the query, not materialized — great for structuring, not for reuse across statements. <strong>Temp table</strong> (<code>#t</code>): real table in tempdb with statistics and indexes — best for large intermediate results used multiple times. <strong>Table variable</strong> (<code>@t</code>): lightweight, but historically poor cardinality estimates made it slow for big row counts — fine for small sets. Interview-safe rule: CTE for clarity, temp table for heavy lifting, table variable for a handful of rows.' },
      { d: 'medium',
        q: 'What are SQL Server\'s transaction isolation levels, and what does NOLOCK really do?',
        a: 'Default is <strong>READ COMMITTED</strong> (readers block on uncommitted writes). Levels trade anomalies for concurrency up through <strong>SERIALIZABLE</strong>; SQL Server also offers <strong>SNAPSHOT</strong> / read-committed-snapshot (RCSI), which gives readers a row version instead of a lock — readers stop blocking writers, similar to Oracle/Postgres MVCC behavior. <code>WITH (NOLOCK)</code> = READ UNCOMMITTED: it reads <strong>dirty, possibly duplicated or skipped rows</strong> during page splits. Saying "NOLOCK is not a performance setting, it\'s a correctness trade — prefer RCSI" is exactly the answer an enterprise .NET shop wants to hear.' },
      { d: 'hard',
        q: 'What is parameter sniffing, and how do you deal with it?',
        a: 'SQL Server compiles a stored procedure\'s plan using the <strong>first parameter values it sees</strong> and caches it. If those values were atypical (one customer with 2M orders), later calls reuse a plan that\'s terrible for typical inputs — the classic "fast in SSMS, slow from the app" mystery. Fixes, in escalating order: <code>OPTION (RECOMPILE)</code> on the problem statement (fresh plan per call, pay compile cost), <code>OPTIMIZE FOR</code> a representative value (or <code>UNKNOWN</code>), rewriting to avoid wildly skewed predicates, or branching to separate procedures per shape. Being able to tell this story end-to-end is a strong senior signal for the Programmer III level.' },
    ],
  },
  {
    id: 'msi-rest',
    title: 'REST API Design',
    desc: 'Both postings require building and consuming RESTful Web APIs. Framework specifics are ASP.NET Core, but the design questions are stack-neutral.',
    questions: [
      { d: 'easy',
        q: 'What makes an API RESTful?',
        a: 'Resources identified by nouns-in-URLs (<code>/api/orders/42</code>), manipulated through the uniform HTTP verb vocabulary, with <strong>stateless</strong> requests (every request carries what\'s needed — no server session), standard status codes, and JSON representations. Mention Richardson maturity briefly: most real APIs are "level 2" (resources + verbs + status codes) and that\'s fine; HATEOAS rarely appears in practice.' },
      { d: 'easy',
        q: 'Walk through the HTTP verbs and which are idempotent.',
        a: '<ul><li><strong>GET</strong> — read, safe and idempotent, cacheable</li><li><strong>POST</strong> — create / non-idempotent actions (two POSTs = two orders)</li><li><strong>PUT</strong> — full replace, <strong>idempotent</strong> (same request twice = same state)</li><li><strong>PATCH</strong> — partial update</li><li><strong>DELETE</strong> — idempotent (deleting twice leaves the same absence; the second may 404)</li></ul>Idempotency matters because clients and proxies <strong>retry</strong>: retrying PUT/DELETE is safe, retrying POST needs an idempotency key or dedup.' },
      { d: 'easy',
        q: 'Which HTTP status codes do you actually use, and when?',
        a: '<strong>200</strong> OK; <strong>201</strong> Created (+ <code>Location</code> header) after POST; <strong>204</strong> No Content for successful DELETE/PUT with no body; <strong>400</strong> validation failure; <strong>401</strong> not authenticated vs <strong>403</strong> authenticated but not allowed — interviewers love this pair; <strong>404</strong> missing resource; <strong>409</strong> conflict (duplicate, concurrent edit); <strong>500</strong> unhandled server error. Principle: 4xx = the caller can fix the request, 5xx = we broke.' },
      { d: 'medium',
        q: 'How do you build a Web API in ASP.NET Core?',
        a: 'Controller class with attribute routing; DI provides services; model binding maps JSON to parameters; <code>[ApiController]</code> adds automatic 400s for invalid models.<div class="ex-label">Example</div><pre><code>[ApiController]\n[Route("api/[controller]")]\npublic class OrdersController : ControllerBase {\n  private readonly IOrderService _svc;\n  public OrdersController(IOrderService svc) =&gt; _svc = svc;\n\n  [HttpGet("{id}")]\n  public async Task&lt;ActionResult&lt;OrderDto&gt;&gt; Get(int id) =&gt;\n    await _svc.FindAsync(id) is { } o ? Ok(o) : NotFound();\n}</code></pre>Structurally identical to Spring: <code>[Route]</code>/<code>[HttpGet]</code> ↔ <code>@RequestMapping</code>/<code>@GetMapping</code>, <code>ActionResult</code> ↔ <code>ResponseEntity</code>. Newer .NET also offers <strong>minimal APIs</strong> (<code>app.MapGet(...)</code>) for small services — worth naming.' },
      { d: 'medium',
        q: 'How would you version a REST API, and which approach would you pick?',
        a: 'Options: <strong>URL path</strong> (<code>/api/v2/orders</code>) — explicit, cache-friendly, easiest to route and debug; <strong>header/media-type</strong> — cleaner URLs but invisible in logs and harder for consumers; <strong>query string</strong> — simple but easy to omit. Default recommendation for an internal enterprise API: URL-path versioning, additive (non-breaking) changes within a version, and a deprecation window before removing v1. ASP.NET Core has <code>Asp.Versioning</code> packages that formalize any of these.' },
      { d: 'medium',
        q: 'Design pagination, filtering, and sorting for a large collection endpoint.',
        a: 'Query parameters on the collection: <code>GET /api/orders?status=open&amp;sort=-orderDate&amp;page=2&amp;pageSize=50</code>, returning items plus paging metadata (total count, page, or next link). <strong>Offset paging</strong> (<code>OFFSET...FETCH</code> in SQL Server) is simple but drifts under concurrent inserts and slows at deep offsets; <strong>keyset/cursor paging</strong> (<code>WHERE OrderDate &lt; @last ORDER BY OrderDate DESC</code>) is stable and index-friendly — the right answer for large tables. Always cap <code>pageSize</code> server-side and whitelist sortable columns to keep queries sargable and safe.' },
      { d: 'medium',
        q: 'How do you secure a REST API?',
        a: 'Authenticate with <strong>JWT bearer tokens</strong>: client obtains a token, sends <code>Authorization: Bearer ...</code>, and ASP.NET Core\'s JWT middleware validates signature/expiry and populates the user — then <code>[Authorize(Roles = "Admin")]</code> gates endpoints (Spring Security\'s filter-chain analog). The Angular interceptor attaches the token on every call. Round out the answer: HTTPS only, validate all input, parameterized queries/EF for injection, CORS locked to known origins, rate limiting, and never leak stack traces in error responses.' },
      { d: 'medium',
        q: 'How should a Web API handle and report errors?',
        a: 'Centrally, not per-controller: exception-handling middleware maps exceptions to responses so controllers stay clean — Spring\'s <code>@ControllerAdvice</code> equivalent. Use <strong>ProblemDetails</strong> (RFC 7807), the standard JSON error shape ASP.NET Core emits natively: <code>{ "title": "Order not found", "status": 404, "traceId": "..." }</code>. Validation failures return 400 with field-level details automatically under <code>[ApiController]</code>. Log the full exception server-side with a correlation/trace id, return only the safe summary to the caller.' },
      { d: 'hard',
        q: 'How do you consume an external HTTP API reliably from .NET?',
        a: 'Use <strong>IHttpClientFactory</strong> (never <code>new HttpClient()</code> per call — socket exhaustion; the factory pools handlers and rotates DNS). Add resilience as delegating handlers via <strong>Polly</strong> / <code>Microsoft.Extensions.Resilience</code>: timeout per attempt, <strong>retry with exponential backoff + jitter for transient failures only</strong> (5xx/timeouts — never blindly retry POSTs), and a <strong>circuit breaker</strong> so a dead dependency fails fast instead of stacking up threads. Flow <code>CancellationToken</code>s so abandoned requests stop downstream work. This is the same resilience story as Resilience4j in Java — say so.' },
      { d: 'easy',
        q: 'What is OpenAPI/Swagger and why does it matter?',
        a: 'A machine-readable description of your API (endpoints, schemas, auth). ASP.NET Core generates it from your controllers (Swashbuckle/NSwag), giving: interactive docs (Swagger UI) for manual testing, generated typed clients — including the TypeScript interfaces the Angular app uses — and a contract for review before code exists. Springdoc does the identical job in Spring, so present it as one habit carried across stacks.' },
    ],
  },
  {
    id: 'msi-practices',
    title: 'Testing, Git & CI/CD',
    desc: 'Both postings list unit testing, Git-based version control, JIRA, and CI/CD; Programmer III explicitly requires proficiency with AI coding assistants.',
    questions: [
      { d: 'easy',
        q: 'Explain unit vs integration vs end-to-end tests, and how you balance them.',
        a: 'The <strong>test pyramid</strong>: many fast <strong>unit tests</strong> (one class/function, dependencies mocked), fewer <strong>integration tests</strong> (real pieces together — API + database), few <strong>end-to-end tests</strong> (browser through the full stack) because they\'re slow and flaky. Unit tests run on every build in seconds; integration tests catch the wiring bugs units can\'t; E2E covers a handful of critical user journeys. The ratio matters less than the principle: push each check to the cheapest level that can catch the bug.' },
      { d: 'medium',
        q: 'How do you write unit and integration tests in .NET?',
        a: '<strong>xUnit</strong> (or NUnit/MSTest) + <strong>Moq</strong> mirrors JUnit + Mockito: <code>[Fact]</code> ↔ <code>@Test</code>, <code>[Theory]</code> with <code>[InlineData]</code> ↔ parameterized tests, Arrange-Act-Assert throughout — DI makes this easy since services depend on interfaces you can mock. For integration tests, <code>WebApplicationFactory&lt;Program&gt;</code> boots the real app in-memory (Spring\'s <code>@SpringBootTest</code> + MockMvc analog) so you hit endpoints through the actual pipeline; pair with a LocalDB/containerized SQL Server for data-layer coverage. Name your habits: test naming conventions, one behavior per test, tests in CI as a merge gate.' },
      { d: 'easy',
        q: 'Describe your Git branching workflow on a team.',
        a: 'Short-lived <strong>feature branches</strong> off <code>main</code>: branch per JIRA ticket, small focused commits, push early, open a <strong>pull request</strong> — CI runs build + tests, at least one peer review, then merge and delete the branch. Keep branches days-old, not weeks (small PRs review better and conflict less). Know the vocabulary of both models — trunk-based (favored with good CI) vs GitFlow (release/hotfix branches, fits scheduled releases) — and say you adapt to the team\'s convention.' },
      { d: 'medium',
        q: 'Merge vs rebase, and how do you resolve a gnarly conflict?',
        a: '<strong>Merge</strong> preserves history with a merge commit; <strong>rebase</strong> replays your commits on the new base for linear history. Safe rule: <strong>rebase your local/feature branch to update it, never rebase shared history</strong>; squash-merge PRs if the team wants one commit per feature. Conflicts: <code>git status</code> to list files, resolve markers in the editor/IDE (understanding <em>both</em> changes, not picking blindly), re-run the tests, then continue. Mention <code>git cherry-pick</code> for porting a hotfix and <code>git bisect</code> for hunting a regression — practical-competence signals.' },
      { d: 'medium',
        q: 'What does a CI/CD pipeline look like for a .NET + Angular app?',
        a: 'On every PR/push (GitHub Actions or Azure DevOps YAML): restore → build (<code>dotnet build</code>, <code>ng build</code>) → unit tests (<code>dotnet test</code>) → package. <strong>CI</strong> = every merge is built and tested automatically, failing fast; <strong>CD</strong> = the pipeline deploys the artifact through environments (dev → QA/staging → prod, with an approval gate before prod). EF Core <strong>migrations run as a deploy step</strong> so schema and code ship together. Sneak in observability: deploys aren\'t done until health checks and logs confirm it.' },
      { d: 'easy',
        q: 'How do you work day-to-day in an Agile team with JIRA?',
        a: 'Sprints (usually 2 weeks): planning breaks stories into estimated tickets; daily standup covers progress/plan/blockers; tickets flow To Do → In Progress → Review → Done, with branch and PR linked to the ticket for traceability; sprint ends in review/demo + retrospective. Good ticket hygiene — acceptance criteria before work starts, comments capturing decisions — is what keeps a multi-project shop like MSI\'s IT team sane. Mention flagging blockers early rather than sitting on them; it\'s the behavioral answer inside the process answer.' },
      { d: 'medium',
        q: 'How do you use AI coding assistants effectively and responsibly? (explicitly required for Programmer III)',
        a: 'Treat them as a fast pair, not an authority. Effective: boilerplate and scaffolding (DTOs, mappings, test skeletons), generating unit-test cases you then curate, explaining unfamiliar code, first-draft SQL/regex, rubber-ducking designs. Responsible: <strong>review and test everything generated</strong> — you own what you commit; never paste secrets or proprietary code into unapproved tools; verify suggested APIs actually exist (hallucinated methods compile in your head, not in the build); follow the company\'s AI policy. Have one concrete story ready — e.g. "Copilot/Claude drafted the test matrix, I caught the edge case it missed" — since MSI asks for demonstrated proficiency, not enthusiasm.' },
      { d: 'medium',
        q: 'What do you look for when reviewing a pull request?',
        a: 'In rough priority: <strong>correctness</strong> (logic, edge cases, error handling, concurrency), <strong>tests</strong> (do they exist, do they test behavior rather than implementation), <strong>security</strong> (input validation, injection, secrets, authz on new endpoints), <strong>readability</strong> (naming, dead code, consistency with the codebase), and performance where it plausibly matters (N+1 queries, missing index for a new query pattern). Review style counts too: comment with reasons and suggestions, distinguish blockers from nits, and keep it about the code, not the author.' },
    ],
  },
];
